
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("484b64a1-eea1-401a-bf61-dcfc4d8f2e16")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("ModeloTablas", "DEPARTAMENTOS_FK1", "PAIS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(PAIS), "DEPARTAMENTOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DEPARTAMENTOS), True)>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "MUNICIPIOS_FK1", "DEPARTAMENTOS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(DEPARTAMENTOS), "MUNICIPIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(MUNICIPIOS), True)>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(OFICINAS), "DETALLE_OFICINA_GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DETALLE_OFICINA_GESTIONES), True)>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(GESTIONES), "DETALLE_OFICINA_GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DETALLE_OFICINA_GESTIONES), True)>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(SUCURSALES), "DETALLE_SUCURSAL_OFICINA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DETALLE_SUCURSAL_OFICINA), True)>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(OFICINAS), "DETALLE_SUCURSAL_OFICINA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DETALLE_SUCURSAL_OFICINA), True)>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(DETALLE_SUCURSAL_OFICINA), "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(USUARIOS), True)>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(DETALLE_SUCURSAL_OFICINA), "VENTANILLAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(VENTANILLAS), True)>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "REQUISITOS_FK1", "GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(GESTIONES), "REQUISITOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(REQUISITOS), True)>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "SUCURSALES_FK1", "MUNICIPIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(MUNICIPIOS), "SUCURSALES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SUCURSALES), True)>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "DETALLE_USUARIOS_PERFILES", "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(USUARIOS), "PERFILES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(PERFILES))>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "GESTIONES_VENTANILLAS", "DETALLE_OFICINA_GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DETALLE_OFICINA_GESTIONES), "VENTANILLAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(VENTANILLAS))>
<Assembly: EdmRelationshipAttribute("ModeloTablas", "SUCURSALES_FK2", "EMPRESAS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(EMPRESAS), "SUCURSALES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SUCURSALES), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class EntidadesTablas
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new EntidadesTablas object using the connection string found in the 'EntidadesTablas' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=EntidadesTablas", "EntidadesTablas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new EntidadesTablas object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "EntidadesTablas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new EntidadesTablas object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "EntidadesTablas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property DEPARTAMENTOS() As ObjectSet(Of DEPARTAMENTOS)
        Get
            If (_DEPARTAMENTOS Is Nothing) Then
                _DEPARTAMENTOS = MyBase.CreateObjectSet(Of DEPARTAMENTOS)("DEPARTAMENTOS")
            End If
            Return _DEPARTAMENTOS
        End Get
    End Property

    Private _DEPARTAMENTOS As ObjectSet(Of DEPARTAMENTOS)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property DETALLE_OFICINA_GESTIONES() As ObjectSet(Of DETALLE_OFICINA_GESTIONES)
        Get
            If (_DETALLE_OFICINA_GESTIONES Is Nothing) Then
                _DETALLE_OFICINA_GESTIONES = MyBase.CreateObjectSet(Of DETALLE_OFICINA_GESTIONES)("DETALLE_OFICINA_GESTIONES")
            End If
            Return _DETALLE_OFICINA_GESTIONES
        End Get
    End Property

    Private _DETALLE_OFICINA_GESTIONES As ObjectSet(Of DETALLE_OFICINA_GESTIONES)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property DETALLE_SUCURSAL_OFICINA() As ObjectSet(Of DETALLE_SUCURSAL_OFICINA)
        Get
            If (_DETALLE_SUCURSAL_OFICINA Is Nothing) Then
                _DETALLE_SUCURSAL_OFICINA = MyBase.CreateObjectSet(Of DETALLE_SUCURSAL_OFICINA)("DETALLE_SUCURSAL_OFICINA")
            End If
            Return _DETALLE_SUCURSAL_OFICINA
        End Get
    End Property

    Private _DETALLE_SUCURSAL_OFICINA As ObjectSet(Of DETALLE_SUCURSAL_OFICINA)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property GESTIONES() As ObjectSet(Of GESTIONES)
        Get
            If (_GESTIONES Is Nothing) Then
                _GESTIONES = MyBase.CreateObjectSet(Of GESTIONES)("GESTIONES")
            End If
            Return _GESTIONES
        End Get
    End Property

    Private _GESTIONES As ObjectSet(Of GESTIONES)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MUNICIPIOS() As ObjectSet(Of MUNICIPIOS)
        Get
            If (_MUNICIPIOS Is Nothing) Then
                _MUNICIPIOS = MyBase.CreateObjectSet(Of MUNICIPIOS)("MUNICIPIOS")
            End If
            Return _MUNICIPIOS
        End Get
    End Property

    Private _MUNICIPIOS As ObjectSet(Of MUNICIPIOS)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property OFICINAS() As ObjectSet(Of OFICINAS)
        Get
            If (_OFICINAS Is Nothing) Then
                _OFICINAS = MyBase.CreateObjectSet(Of OFICINAS)("OFICINAS")
            End If
            Return _OFICINAS
        End Get
    End Property

    Private _OFICINAS As ObjectSet(Of OFICINAS)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property PAIS() As ObjectSet(Of PAIS)
        Get
            If (_PAIS Is Nothing) Then
                _PAIS = MyBase.CreateObjectSet(Of PAIS)("PAIS")
            End If
            Return _PAIS
        End Get
    End Property

    Private _PAIS As ObjectSet(Of PAIS)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property PERFILES() As ObjectSet(Of PERFILES)
        Get
            If (_PERFILES Is Nothing) Then
                _PERFILES = MyBase.CreateObjectSet(Of PERFILES)("PERFILES")
            End If
            Return _PERFILES
        End Get
    End Property

    Private _PERFILES As ObjectSet(Of PERFILES)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property REQUISITOS() As ObjectSet(Of REQUISITOS)
        Get
            If (_REQUISITOS Is Nothing) Then
                _REQUISITOS = MyBase.CreateObjectSet(Of REQUISITOS)("REQUISITOS")
            End If
            Return _REQUISITOS
        End Get
    End Property

    Private _REQUISITOS As ObjectSet(Of REQUISITOS)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SUCURSALES() As ObjectSet(Of SUCURSALES)
        Get
            If (_SUCURSALES Is Nothing) Then
                _SUCURSALES = MyBase.CreateObjectSet(Of SUCURSALES)("SUCURSALES")
            End If
            Return _SUCURSALES
        End Get
    End Property

    Private _SUCURSALES As ObjectSet(Of SUCURSALES)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property USUARIOS() As ObjectSet(Of USUARIOS)
        Get
            If (_USUARIOS Is Nothing) Then
                _USUARIOS = MyBase.CreateObjectSet(Of USUARIOS)("USUARIOS")
            End If
            Return _USUARIOS
        End Get
    End Property

    Private _USUARIOS As ObjectSet(Of USUARIOS)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property VENTANILLAS() As ObjectSet(Of VENTANILLAS)
        Get
            If (_VENTANILLAS Is Nothing) Then
                _VENTANILLAS = MyBase.CreateObjectSet(Of VENTANILLAS)("VENTANILLAS")
            End If
            Return _VENTANILLAS
        End Get
    End Property

    Private _VENTANILLAS As ObjectSet(Of VENTANILLAS)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property EMPRESAS() As ObjectSet(Of EMPRESAS)
        Get
            If (_EMPRESAS Is Nothing) Then
                _EMPRESAS = MyBase.CreateObjectSet(Of EMPRESAS)("EMPRESAS")
            End If
            Return _EMPRESAS
        End Get
    End Property

    Private _EMPRESAS As ObjectSet(Of EMPRESAS)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the DEPARTAMENTOS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDEPARTAMENTOS(ByVal dEPARTAMENTOS As DEPARTAMENTOS)
        MyBase.AddObject("DEPARTAMENTOS", dEPARTAMENTOS)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the DETALLE_OFICINA_GESTIONES EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDETALLE_OFICINA_GESTIONES(ByVal dETALLE_OFICINA_GESTIONES As DETALLE_OFICINA_GESTIONES)
        MyBase.AddObject("DETALLE_OFICINA_GESTIONES", dETALLE_OFICINA_GESTIONES)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the DETALLE_SUCURSAL_OFICINA EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDETALLE_SUCURSAL_OFICINA(ByVal dETALLE_SUCURSAL_OFICINA As DETALLE_SUCURSAL_OFICINA)
        MyBase.AddObject("DETALLE_SUCURSAL_OFICINA", dETALLE_SUCURSAL_OFICINA)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the GESTIONES EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToGESTIONES(ByVal gESTIONES As GESTIONES)
        MyBase.AddObject("GESTIONES", gESTIONES)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MUNICIPIOS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMUNICIPIOS(ByVal mUNICIPIOS As MUNICIPIOS)
        MyBase.AddObject("MUNICIPIOS", mUNICIPIOS)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the OFICINAS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToOFICINAS(ByVal oFICINAS As OFICINAS)
        MyBase.AddObject("OFICINAS", oFICINAS)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the PAIS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToPAIS(ByVal pAIS As PAIS)
        MyBase.AddObject("PAIS", pAIS)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the PERFILES EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToPERFILES(ByVal pERFILES As PERFILES)
        MyBase.AddObject("PERFILES", pERFILES)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the REQUISITOS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToREQUISITOS(ByVal rEQUISITOS As REQUISITOS)
        MyBase.AddObject("REQUISITOS", rEQUISITOS)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the SUCURSALES EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSUCURSALES(ByVal sUCURSALES As SUCURSALES)
        MyBase.AddObject("SUCURSALES", sUCURSALES)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the USUARIOS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToUSUARIOS(ByVal uSUARIOS As USUARIOS)
        MyBase.AddObject("USUARIOS", uSUARIOS)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the VENTANILLAS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToVENTANILLAS(ByVal vENTANILLAS As VENTANILLAS)
        MyBase.AddObject("VENTANILLAS", vENTANILLAS)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the EMPRESAS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToEMPRESAS(ByVal eMPRESAS As EMPRESAS)
        MyBase.AddObject("EMPRESAS", eMPRESAS)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="DEPARTAMENTOS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DEPARTAMENTOS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new DEPARTAMENTOS object.
    ''' </summary>
    ''' <param name="iDDEPARTAMENTO">Initial value of the IDDEPARTAMENTO property.</param>
    ''' <param name="iDPAIS">Initial value of the IDPAIS property.</param>
    ''' <param name="cODIGO_DEPTO">Initial value of the CODIGO_DEPTO property.</param>
    ''' <param name="nOMBRE_DEPTO">Initial value of the NOMBRE_DEPTO property.</param>
    Public Shared Function CreateDEPARTAMENTOS(iDDEPARTAMENTO As Global.System.Decimal, iDPAIS As Global.System.Decimal, cODIGO_DEPTO As Global.System.String, nOMBRE_DEPTO As Global.System.String) As DEPARTAMENTOS
        Dim dEPARTAMENTOS as DEPARTAMENTOS = New DEPARTAMENTOS
        dEPARTAMENTOS.IDDEPARTAMENTO = iDDEPARTAMENTO
        dEPARTAMENTOS.IDPAIS = iDPAIS
        dEPARTAMENTOS.CODIGO_DEPTO = cODIGO_DEPTO
        dEPARTAMENTOS.NOMBRE_DEPTO = nOMBRE_DEPTO
        Return dEPARTAMENTOS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDEPARTAMENTO() As Global.System.Decimal
        Get
            Return _IDDEPARTAMENTO
        End Get
        Set
            If (_IDDEPARTAMENTO <> Value) Then
                OnIDDEPARTAMENTOChanging(value)
                ReportPropertyChanging("IDDEPARTAMENTO")
                _IDDEPARTAMENTO = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDDEPARTAMENTO")
                OnIDDEPARTAMENTOChanged()
            End If
        End Set
    End Property

    Private _IDDEPARTAMENTO As Global.System.Decimal
    Private Partial Sub OnIDDEPARTAMENTOChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDEPARTAMENTOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDPAIS() As Global.System.Decimal
        Get
            Return _IDPAIS
        End Get
        Set
            OnIDPAISChanging(value)
            ReportPropertyChanging("IDPAIS")
            _IDPAIS = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDPAIS")
            OnIDPAISChanged()
        End Set
    End Property

    Private _IDPAIS As Global.System.Decimal
    Private Partial Sub OnIDPAISChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDPAISChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CODIGO_DEPTO() As Global.System.String
        Get
            Return _CODIGO_DEPTO
        End Get
        Set
            OnCODIGO_DEPTOChanging(value)
            ReportPropertyChanging("CODIGO_DEPTO")
            _CODIGO_DEPTO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("CODIGO_DEPTO")
            OnCODIGO_DEPTOChanged()
        End Set
    End Property

    Private _CODIGO_DEPTO As Global.System.String
    Private Partial Sub OnCODIGO_DEPTOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCODIGO_DEPTOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NOMBRE_DEPTO() As Global.System.String
        Get
            Return _NOMBRE_DEPTO
        End Get
        Set
            OnNOMBRE_DEPTOChanging(value)
            ReportPropertyChanging("NOMBRE_DEPTO")
            _NOMBRE_DEPTO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NOMBRE_DEPTO")
            OnNOMBRE_DEPTOChanged()
        End Set
    End Property

    Private _NOMBRE_DEPTO As Global.System.String
    Private Partial Sub OnNOMBRE_DEPTOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_DEPTOChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DEPARTAMENTOS_FK1", "PAIS")>
    Public Property PAIS() As PAIS
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of PAIS)("ModeloTablas.DEPARTAMENTOS_FK1", "PAIS").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of PAIS)("ModeloTablas.DEPARTAMENTOS_FK1", "PAIS").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PAISReference() As EntityReference(Of PAIS)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of PAIS)("ModeloTablas.DEPARTAMENTOS_FK1", "PAIS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of PAIS)("ModeloTablas.DEPARTAMENTOS_FK1", "PAIS", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "MUNICIPIOS_FK1", "MUNICIPIOS")>
     Public Property MUNICIPIOS() As EntityCollection(Of MUNICIPIOS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of MUNICIPIOS)("ModeloTablas.MUNICIPIOS_FK1", "MUNICIPIOS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of MUNICIPIOS)("ModeloTablas.MUNICIPIOS_FK1", "MUNICIPIOS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="DETALLE_OFICINA_GESTIONES")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DETALLE_OFICINA_GESTIONES
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new DETALLE_OFICINA_GESTIONES object.
    ''' </summary>
    ''' <param name="iDDETALLE_OFICINA_GESTION">Initial value of the IDDETALLE_OFICINA_GESTION property.</param>
    Public Shared Function CreateDETALLE_OFICINA_GESTIONES(iDDETALLE_OFICINA_GESTION As Global.System.Decimal) As DETALLE_OFICINA_GESTIONES
        Dim dETALLE_OFICINA_GESTIONES as DETALLE_OFICINA_GESTIONES = New DETALLE_OFICINA_GESTIONES
        dETALLE_OFICINA_GESTIONES.IDDETALLE_OFICINA_GESTION = iDDETALLE_OFICINA_GESTION
        Return dETALLE_OFICINA_GESTIONES
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_OFICINA_GESTION() As Global.System.Decimal
        Get
            Return _IDDETALLE_OFICINA_GESTION
        End Get
        Set
            If (_IDDETALLE_OFICINA_GESTION <> Value) Then
                OnIDDETALLE_OFICINA_GESTIONChanging(value)
                ReportPropertyChanging("IDDETALLE_OFICINA_GESTION")
                _IDDETALLE_OFICINA_GESTION = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDDETALLE_OFICINA_GESTION")
                OnIDDETALLE_OFICINA_GESTIONChanged()
            End If
        End Set
    End Property

    Private _IDDETALLE_OFICINA_GESTION As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_OFICINA_GESTIONChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_OFICINA_GESTIONChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDOFICINA() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDOFICINA
        End Get
        Set
            OnIDOFICINAChanging(value)
            ReportPropertyChanging("IDOFICINA")
            _IDOFICINA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDOFICINA")
            OnIDOFICINAChanged()
        End Set
    End Property

    Private _IDOFICINA As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDOFICINAChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDOFICINAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDGESTION() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDGESTION
        End Get
        Set
            OnIDGESTIONChanging(value)
            ReportPropertyChanging("IDGESTION")
            _IDGESTION = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDGESTION")
            OnIDGESTIONChanged()
        End Set
    End Property

    Private _IDGESTION As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDGESTIONChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDGESTIONChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS")>
    Public Property OFICINAS() As OFICINAS
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OFICINASReference() As EntityReference(Of OFICINAS)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of OFICINAS)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES")>
    Public Property GESTIONES() As GESTIONES
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property GESTIONESReference() As EntityReference(Of GESTIONES)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of GESTIONES)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "GESTIONES_VENTANILLAS", "VENTANILLAS")>
     Public Property VENTANILLAS() As EntityCollection(Of VENTANILLAS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of VENTANILLAS)("ModeloTablas.GESTIONES_VENTANILLAS", "VENTANILLAS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of VENTANILLAS)("ModeloTablas.GESTIONES_VENTANILLAS", "VENTANILLAS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="DETALLE_SUCURSAL_OFICINA")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DETALLE_SUCURSAL_OFICINA
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new DETALLE_SUCURSAL_OFICINA object.
    ''' </summary>
    ''' <param name="iDDETALLE_SUCURSAL_OFICINA">Initial value of the IDDETALLE_SUCURSAL_OFICINA property.</param>
    Public Shared Function CreateDETALLE_SUCURSAL_OFICINA(iDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal) As DETALLE_SUCURSAL_OFICINA
        Dim dETALLE_SUCURSAL_OFICINA as DETALLE_SUCURSAL_OFICINA = New DETALLE_SUCURSAL_OFICINA
        dETALLE_SUCURSAL_OFICINA.IDDETALLE_SUCURSAL_OFICINA = iDDETALLE_SUCURSAL_OFICINA
        Return dETALLE_SUCURSAL_OFICINA
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_SUCURSAL_OFICINA() As Global.System.Decimal
        Get
            Return _IDDETALLE_SUCURSAL_OFICINA
        End Get
        Set
            If (_IDDETALLE_SUCURSAL_OFICINA <> Value) Then
                OnIDDETALLE_SUCURSAL_OFICINAChanging(value)
                ReportPropertyChanging("IDDETALLE_SUCURSAL_OFICINA")
                _IDDETALLE_SUCURSAL_OFICINA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDDETALLE_SUCURSAL_OFICINA")
                OnIDDETALLE_SUCURSAL_OFICINAChanged()
            End If
        End Set
    End Property

    Private _IDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDSUCURSAL() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDSUCURSAL
        End Get
        Set
            OnIDSUCURSALChanging(value)
            ReportPropertyChanging("IDSUCURSAL")
            _IDSUCURSAL = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDSUCURSAL")
            OnIDSUCURSALChanged()
        End Set
    End Property

    Private _IDSUCURSAL As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDSUCURSALChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDSUCURSALChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDOFICINA() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDOFICINA
        End Get
        Set
            OnIDOFICINAChanging(value)
            ReportPropertyChanging("IDOFICINA")
            _IDOFICINA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDOFICINA")
            OnIDOFICINAChanged()
        End Set
    End Property

    Private _IDOFICINA As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDOFICINAChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDOFICINAChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES")>
    Public Property SUCURSALES() As SUCURSALES
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SUCURSALES)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SUCURSALES)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SUCURSALESReference() As EntityReference(Of SUCURSALES)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SUCURSALES)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SUCURSALES)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS")>
    Public Property OFICINAS() As OFICINAS
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OFICINASReference() As EntityReference(Of OFICINAS)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of OFICINAS)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "USUARIOS_FK1", "USUARIOS")>
     Public Property USUARIOS() As EntityCollection(Of USUARIOS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of USUARIOS)("ModeloTablas.USUARIOS_FK1", "USUARIOS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of USUARIOS)("ModeloTablas.USUARIOS_FK1", "USUARIOS", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "VENTANILLAS_FK1", "VENTANILLAS")>
     Public Property VENTANILLAS() As EntityCollection(Of VENTANILLAS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of VENTANILLAS)("ModeloTablas.VENTANILLAS_FK1", "VENTANILLAS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of VENTANILLAS)("ModeloTablas.VENTANILLAS_FK1", "VENTANILLAS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="EMPRESAS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class EMPRESAS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new EMPRESAS object.
    ''' </summary>
    ''' <param name="iDEMPRESA">Initial value of the IDEMPRESA property.</param>
    Public Shared Function CreateEMPRESAS(iDEMPRESA As Global.System.Decimal) As EMPRESAS
        Dim eMPRESAS as EMPRESAS = New EMPRESAS
        eMPRESAS.IDEMPRESA = iDEMPRESA
        Return eMPRESAS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDEMPRESA() As Global.System.Decimal
        Get
            Return _IDEMPRESA
        End Get
        Set
            If (_IDEMPRESA <> Value) Then
                OnIDEMPRESAChanging(value)
                ReportPropertyChanging("IDEMPRESA")
                _IDEMPRESA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDEMPRESA")
                OnIDEMPRESAChanged()
            End If
        End Set
    End Property

    Private _IDEMPRESA As Global.System.Decimal
    Private Partial Sub OnIDEMPRESAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDEMPRESAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            OnNOMBREChanging(value)
            ReportPropertyChanging("NOMBRE")
            _NOMBRE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE")
            OnNOMBREChanged()
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LOGO() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_LOGO)
        End Get
        Set
            OnLOGOChanging(value)
            ReportPropertyChanging("LOGO")
            _LOGO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("LOGO")
            OnLOGOChanged()
        End Set
    End Property

    Private _LOGO As Global.System.Byte()
    Private Partial Sub OnLOGOChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnLOGOChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "SUCURSALES_FK2", "SUCURSALES")>
     Public Property SUCURSALES() As EntityCollection(Of SUCURSALES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SUCURSALES)("ModeloTablas.SUCURSALES_FK2", "SUCURSALES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SUCURSALES)("ModeloTablas.SUCURSALES_FK2", "SUCURSALES", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="GESTIONES")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class GESTIONES
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new GESTIONES object.
    ''' </summary>
    ''' <param name="iDGESTION">Initial value of the IDGESTION property.</param>
    Public Shared Function CreateGESTIONES(iDGESTION As Global.System.Decimal) As GESTIONES
        Dim gESTIONES as GESTIONES = New GESTIONES
        gESTIONES.IDGESTION = iDGESTION
        Return gESTIONES
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDGESTION() As Global.System.Decimal
        Get
            Return _IDGESTION
        End Get
        Set
            If (_IDGESTION <> Value) Then
                OnIDGESTIONChanging(value)
                ReportPropertyChanging("IDGESTION")
                _IDGESTION = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDGESTION")
                OnIDGESTIONChanged()
            End If
        End Set
    End Property

    Private _IDGESTION As Global.System.Decimal
    Private Partial Sub OnIDGESTIONChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDGESTIONChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CODIGO() As Global.System.String
        Get
            Return _CODIGO
        End Get
        Set
            OnCODIGOChanging(value)
            ReportPropertyChanging("CODIGO")
            _CODIGO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CODIGO")
            OnCODIGOChanged()
        End Set
    End Property

    Private _CODIGO As Global.System.String
    Private Partial Sub OnCODIGOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCODIGOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            OnNOMBREChanging(value)
            ReportPropertyChanging("NOMBRE")
            _NOMBRE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE")
            OnNOMBREChanged()
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TIEMPO() As Nullable(Of Global.System.Decimal)
        Get
            Return _TIEMPO
        End Get
        Set
            OnTIEMPOChanging(value)
            ReportPropertyChanging("TIEMPO")
            _TIEMPO = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TIEMPO")
            OnTIEMPOChanged()
        End Set
    End Property

    Private _TIEMPO As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnTIEMPOChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnTIEMPOChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DETALLE_OFICINA_GESTIONES_FK2", "DETALLE_OFICINA_GESTIONES")>
     Public Property DETALLE_OFICINA_GESTIONES() As EntityCollection(Of DETALLE_OFICINA_GESTIONES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK2", "DETALLE_OFICINA_GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK2", "DETALLE_OFICINA_GESTIONES", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "REQUISITOS_FK1", "REQUISITOS")>
     Public Property REQUISITOS() As EntityCollection(Of REQUISITOS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of REQUISITOS)("ModeloTablas.REQUISITOS_FK1", "REQUISITOS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of REQUISITOS)("ModeloTablas.REQUISITOS_FK1", "REQUISITOS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="MUNICIPIOS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MUNICIPIOS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MUNICIPIOS object.
    ''' </summary>
    ''' <param name="iDMUNICIPIO">Initial value of the IDMUNICIPIO property.</param>
    Public Shared Function CreateMUNICIPIOS(iDMUNICIPIO As Global.System.Decimal) As MUNICIPIOS
        Dim mUNICIPIOS as MUNICIPIOS = New MUNICIPIOS
        mUNICIPIOS.IDMUNICIPIO = iDMUNICIPIO
        Return mUNICIPIOS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDMUNICIPIO() As Global.System.Decimal
        Get
            Return _IDMUNICIPIO
        End Get
        Set
            If (_IDMUNICIPIO <> Value) Then
                OnIDMUNICIPIOChanging(value)
                ReportPropertyChanging("IDMUNICIPIO")
                _IDMUNICIPIO = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDMUNICIPIO")
                OnIDMUNICIPIOChanged()
            End If
        End Set
    End Property

    Private _IDMUNICIPIO As Global.System.Decimal
    Private Partial Sub OnIDMUNICIPIOChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDMUNICIPIOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDDEPARTAMENTO() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDDEPARTAMENTO
        End Get
        Set
            OnIDDEPARTAMENTOChanging(value)
            ReportPropertyChanging("IDDEPARTAMENTO")
            _IDDEPARTAMENTO = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDDEPARTAMENTO")
            OnIDDEPARTAMENTOChanged()
        End Set
    End Property

    Private _IDDEPARTAMENTO As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDDEPARTAMENTOChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDDEPARTAMENTOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CODIGO_MPIO() As Global.System.String
        Get
            Return _CODIGO_MPIO
        End Get
        Set
            OnCODIGO_MPIOChanging(value)
            ReportPropertyChanging("CODIGO_MPIO")
            _CODIGO_MPIO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CODIGO_MPIO")
            OnCODIGO_MPIOChanged()
        End Set
    End Property

    Private _CODIGO_MPIO As Global.System.String
    Private Partial Sub OnCODIGO_MPIOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCODIGO_MPIOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE_MPIO() As Global.System.String
        Get
            Return _NOMBRE_MPIO
        End Get
        Set
            OnNOMBRE_MPIOChanging(value)
            ReportPropertyChanging("NOMBRE_MPIO")
            _NOMBRE_MPIO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE_MPIO")
            OnNOMBRE_MPIOChanged()
        End Set
    End Property

    Private _NOMBRE_MPIO As Global.System.String
    Private Partial Sub OnNOMBRE_MPIOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_MPIOChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "MUNICIPIOS_FK1", "DEPARTAMENTOS")>
    Public Property DEPARTAMENTOS() As DEPARTAMENTOS
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DEPARTAMENTOS)("ModeloTablas.MUNICIPIOS_FK1", "DEPARTAMENTOS").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DEPARTAMENTOS)("ModeloTablas.MUNICIPIOS_FK1", "DEPARTAMENTOS").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property DEPARTAMENTOSReference() As EntityReference(Of DEPARTAMENTOS)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DEPARTAMENTOS)("ModeloTablas.MUNICIPIOS_FK1", "DEPARTAMENTOS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of DEPARTAMENTOS)("ModeloTablas.MUNICIPIOS_FK1", "DEPARTAMENTOS", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "SUCURSALES_FK1", "SUCURSALES")>
     Public Property SUCURSALES() As EntityCollection(Of SUCURSALES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SUCURSALES)("ModeloTablas.SUCURSALES_FK1", "SUCURSALES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SUCURSALES)("ModeloTablas.SUCURSALES_FK1", "SUCURSALES", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="OFICINAS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class OFICINAS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new OFICINAS object.
    ''' </summary>
    ''' <param name="iDOFICINA">Initial value of the IDOFICINA property.</param>
    Public Shared Function CreateOFICINAS(iDOFICINA As Global.System.Decimal) As OFICINAS
        Dim oFICINAS as OFICINAS = New OFICINAS
        oFICINAS.IDOFICINA = iDOFICINA
        Return oFICINAS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDOFICINA() As Global.System.Decimal
        Get
            Return _IDOFICINA
        End Get
        Set
            If (_IDOFICINA <> Value) Then
                OnIDOFICINAChanging(value)
                ReportPropertyChanging("IDOFICINA")
                _IDOFICINA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDOFICINA")
                OnIDOFICINAChanged()
            End If
        End Set
    End Property

    Private _IDOFICINA As Global.System.Decimal
    Private Partial Sub OnIDOFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDOFICINAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE_OFICINA() As Global.System.String
        Get
            Return _NOMBRE_OFICINA
        End Get
        Set
            OnNOMBRE_OFICINAChanging(value)
            ReportPropertyChanging("NOMBRE_OFICINA")
            _NOMBRE_OFICINA = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE_OFICINA")
            OnNOMBRE_OFICINAChanged()
        End Set
    End Property

    Private _NOMBRE_OFICINA As Global.System.String
    Private Partial Sub OnNOMBRE_OFICINAChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_OFICINAChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DETALLE_OFICINA_GESTIONES_FK1", "DETALLE_OFICINA_GESTIONES")>
     Public Property DETALLE_OFICINA_GESTIONES() As EntityCollection(Of DETALLE_OFICINA_GESTIONES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK1", "DETALLE_OFICINA_GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("ModeloTablas.DETALLE_OFICINA_GESTIONES_FK1", "DETALLE_OFICINA_GESTIONES", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DETALLE_SUCURSAL_OFICINA_FK2", "DETALLE_SUCURSAL_OFICINA")>
     Public Property DETALLE_SUCURSAL_OFICINA() As EntityCollection(Of DETALLE_SUCURSAL_OFICINA)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK2", "DETALLE_SUCURSAL_OFICINA")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK2", "DETALLE_SUCURSAL_OFICINA", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="PAIS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class PAIS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new PAIS object.
    ''' </summary>
    ''' <param name="iDPAIS">Initial value of the IDPAIS property.</param>
    Public Shared Function CreatePAIS(iDPAIS As Global.System.Decimal) As PAIS
        Dim pAIS as PAIS = New PAIS
        pAIS.IDPAIS = iDPAIS
        Return pAIS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDPAIS() As Global.System.Decimal
        Get
            Return _IDPAIS
        End Get
        Set
            If (_IDPAIS <> Value) Then
                OnIDPAISChanging(value)
                ReportPropertyChanging("IDPAIS")
                _IDPAIS = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDPAIS")
                OnIDPAISChanged()
            End If
        End Set
    End Property

    Private _IDPAIS As Global.System.Decimal
    Private Partial Sub OnIDPAISChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDPAISChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            OnNOMBREChanging(value)
            ReportPropertyChanging("NOMBRE")
            _NOMBRE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE")
            OnNOMBREChanged()
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DEPARTAMENTOS_FK1", "DEPARTAMENTOS")>
     Public Property DEPARTAMENTOS() As EntityCollection(Of DEPARTAMENTOS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DEPARTAMENTOS)("ModeloTablas.DEPARTAMENTOS_FK1", "DEPARTAMENTOS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DEPARTAMENTOS)("ModeloTablas.DEPARTAMENTOS_FK1", "DEPARTAMENTOS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="PERFILES")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class PERFILES
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new PERFILES object.
    ''' </summary>
    ''' <param name="iDPERFIL">Initial value of the IDPERFIL property.</param>
    Public Shared Function CreatePERFILES(iDPERFIL As Global.System.Decimal) As PERFILES
        Dim pERFILES as PERFILES = New PERFILES
        pERFILES.IDPERFIL = iDPERFIL
        Return pERFILES
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDPERFIL() As Global.System.Decimal
        Get
            Return _IDPERFIL
        End Get
        Set
            If (_IDPERFIL <> Value) Then
                OnIDPERFILChanging(value)
                ReportPropertyChanging("IDPERFIL")
                _IDPERFIL = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDPERFIL")
                OnIDPERFILChanged()
            End If
        End Set
    End Property

    Private _IDPERFIL As Global.System.Decimal
    Private Partial Sub OnIDPERFILChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDPERFILChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE_PERFIL() As Global.System.String
        Get
            Return _NOMBRE_PERFIL
        End Get
        Set
            OnNOMBRE_PERFILChanging(value)
            ReportPropertyChanging("NOMBRE_PERFIL")
            _NOMBRE_PERFIL = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE_PERFIL")
            OnNOMBRE_PERFILChanged()
        End Set
    End Property

    Private _NOMBRE_PERFIL As Global.System.String
    Private Partial Sub OnNOMBRE_PERFILChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_PERFILChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DETALLE_USUARIOS_PERFILES", "USUARIOS")>
     Public Property USUARIOS() As EntityCollection(Of USUARIOS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of USUARIOS)("ModeloTablas.DETALLE_USUARIOS_PERFILES", "USUARIOS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of USUARIOS)("ModeloTablas.DETALLE_USUARIOS_PERFILES", "USUARIOS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="REQUISITOS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class REQUISITOS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new REQUISITOS object.
    ''' </summary>
    ''' <param name="iDREQUISITO">Initial value of the IDREQUISITO property.</param>
    Public Shared Function CreateREQUISITOS(iDREQUISITO As Global.System.Decimal) As REQUISITOS
        Dim rEQUISITOS as REQUISITOS = New REQUISITOS
        rEQUISITOS.IDREQUISITO = iDREQUISITO
        Return rEQUISITOS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDREQUISITO() As Global.System.Decimal
        Get
            Return _IDREQUISITO
        End Get
        Set
            If (_IDREQUISITO <> Value) Then
                OnIDREQUISITOChanging(value)
                ReportPropertyChanging("IDREQUISITO")
                _IDREQUISITO = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDREQUISITO")
                OnIDREQUISITOChanged()
            End If
        End Set
    End Property

    Private _IDREQUISITO As Global.System.Decimal
    Private Partial Sub OnIDREQUISITOChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDREQUISITOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDGESTION() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDGESTION
        End Get
        Set
            OnIDGESTIONChanging(value)
            ReportPropertyChanging("IDGESTION")
            _IDGESTION = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDGESTION")
            OnIDGESTIONChanged()
        End Set
    End Property

    Private _IDGESTION As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDGESTIONChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDGESTIONChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE_REQUISITO() As Global.System.String
        Get
            Return _NOMBRE_REQUISITO
        End Get
        Set
            OnNOMBRE_REQUISITOChanging(value)
            ReportPropertyChanging("NOMBRE_REQUISITO")
            _NOMBRE_REQUISITO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE_REQUISITO")
            OnNOMBRE_REQUISITOChanged()
        End Set
    End Property

    Private _NOMBRE_REQUISITO As Global.System.String
    Private Partial Sub OnNOMBRE_REQUISITOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_REQUISITOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property OPCIONAL() As Nullable(Of Global.System.Decimal)
        Get
            Return _OPCIONAL
        End Get
        Set
            OnOPCIONALChanging(value)
            ReportPropertyChanging("OPCIONAL")
            _OPCIONAL = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("OPCIONAL")
            OnOPCIONALChanged()
        End Set
    End Property

    Private _OPCIONAL As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnOPCIONALChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnOPCIONALChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "REQUISITOS_FK1", "GESTIONES")>
    Public Property GESTIONES() As GESTIONES
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("ModeloTablas.REQUISITOS_FK1", "GESTIONES").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("ModeloTablas.REQUISITOS_FK1", "GESTIONES").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property GESTIONESReference() As EntityReference(Of GESTIONES)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("ModeloTablas.REQUISITOS_FK1", "GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of GESTIONES)("ModeloTablas.REQUISITOS_FK1", "GESTIONES", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="SUCURSALES")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SUCURSALES
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new SUCURSALES object.
    ''' </summary>
    ''' <param name="iDSUCURSAL">Initial value of the IDSUCURSAL property.</param>
    ''' <param name="iDEMPRESA">Initial value of the IDEMPRESA property.</param>
    ''' <param name="nOMBRE">Initial value of the NOMBRE property.</param>
    ''' <param name="dIRECCION">Initial value of the DIRECCION property.</param>
    ''' <param name="iDMUNICIPIO">Initial value of the IDMUNICIPIO property.</param>
    Public Shared Function CreateSUCURSALES(iDSUCURSAL As Global.System.Decimal, iDEMPRESA As Global.System.Decimal, nOMBRE As Global.System.String, dIRECCION As Global.System.String, iDMUNICIPIO As Global.System.Decimal) As SUCURSALES
        Dim sUCURSALES as SUCURSALES = New SUCURSALES
        sUCURSALES.IDSUCURSAL = iDSUCURSAL
        sUCURSALES.IDEMPRESA = iDEMPRESA
        sUCURSALES.NOMBRE = nOMBRE
        sUCURSALES.DIRECCION = dIRECCION
        sUCURSALES.IDMUNICIPIO = iDMUNICIPIO
        Return sUCURSALES
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDSUCURSAL() As Global.System.Decimal
        Get
            Return _IDSUCURSAL
        End Get
        Set
            If (_IDSUCURSAL <> Value) Then
                OnIDSUCURSALChanging(value)
                ReportPropertyChanging("IDSUCURSAL")
                _IDSUCURSAL = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDSUCURSAL")
                OnIDSUCURSALChanged()
            End If
        End Set
    End Property

    Private _IDSUCURSAL As Global.System.Decimal
    Private Partial Sub OnIDSUCURSALChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDSUCURSALChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDEMPRESA() As Global.System.Decimal
        Get
            Return _IDEMPRESA
        End Get
        Set
            OnIDEMPRESAChanging(value)
            ReportPropertyChanging("IDEMPRESA")
            _IDEMPRESA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDEMPRESA")
            OnIDEMPRESAChanged()
        End Set
    End Property

    Private _IDEMPRESA As Global.System.Decimal
    Private Partial Sub OnIDEMPRESAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDEMPRESAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            OnNOMBREChanging(value)
            ReportPropertyChanging("NOMBRE")
            _NOMBRE = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NOMBRE")
            OnNOMBREChanged()
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DIRECCION() As Global.System.String
        Get
            Return _DIRECCION
        End Get
        Set
            OnDIRECCIONChanging(value)
            ReportPropertyChanging("DIRECCION")
            _DIRECCION = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("DIRECCION")
            OnDIRECCIONChanged()
        End Set
    End Property

    Private _DIRECCION As Global.System.String
    Private Partial Sub OnDIRECCIONChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDIRECCIONChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDMUNICIPIO() As Global.System.Decimal
        Get
            Return _IDMUNICIPIO
        End Get
        Set
            OnIDMUNICIPIOChanging(value)
            ReportPropertyChanging("IDMUNICIPIO")
            _IDMUNICIPIO = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDMUNICIPIO")
            OnIDMUNICIPIOChanged()
        End Set
    End Property

    Private _IDMUNICIPIO As Global.System.Decimal
    Private Partial Sub OnIDMUNICIPIOChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDMUNICIPIOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LATITUD() As Nullable(Of Global.System.Decimal)
        Get
            Return _LATITUD
        End Get
        Set
            OnLATITUDChanging(value)
            ReportPropertyChanging("LATITUD")
            _LATITUD = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LATITUD")
            OnLATITUDChanged()
        End Set
    End Property

    Private _LATITUD As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnLATITUDChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnLATITUDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LONGITUD() As Nullable(Of Global.System.Decimal)
        Get
            Return _LONGITUD
        End Get
        Set
            OnLONGITUDChanging(value)
            ReportPropertyChanging("LONGITUD")
            _LONGITUD = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LONGITUD")
            OnLONGITUDChanged()
        End Set
    End Property

    Private _LONGITUD As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnLONGITUDChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnLONGITUDChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DETALLE_SUCURSAL_OFICINA_FK1", "DETALLE_SUCURSAL_OFICINA")>
     Public Property DETALLE_SUCURSAL_OFICINA() As EntityCollection(Of DETALLE_SUCURSAL_OFICINA)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK1", "DETALLE_SUCURSAL_OFICINA")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.DETALLE_SUCURSAL_OFICINA_FK1", "DETALLE_SUCURSAL_OFICINA", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "SUCURSALES_FK1", "MUNICIPIOS")>
    Public Property MUNICIPIOS() As MUNICIPIOS
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MUNICIPIOS)("ModeloTablas.SUCURSALES_FK1", "MUNICIPIOS").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MUNICIPIOS)("ModeloTablas.SUCURSALES_FK1", "MUNICIPIOS").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property MUNICIPIOSReference() As EntityReference(Of MUNICIPIOS)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MUNICIPIOS)("ModeloTablas.SUCURSALES_FK1", "MUNICIPIOS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of MUNICIPIOS)("ModeloTablas.SUCURSALES_FK1", "MUNICIPIOS", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "SUCURSALES_FK2", "EMPRESAS")>
    Public Property EMPRESAS() As EMPRESAS
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EMPRESAS)("ModeloTablas.SUCURSALES_FK2", "EMPRESAS").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EMPRESAS)("ModeloTablas.SUCURSALES_FK2", "EMPRESAS").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property EMPRESASReference() As EntityReference(Of EMPRESAS)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of EMPRESAS)("ModeloTablas.SUCURSALES_FK2", "EMPRESAS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of EMPRESAS)("ModeloTablas.SUCURSALES_FK2", "EMPRESAS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="USUARIOS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class USUARIOS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new USUARIOS object.
    ''' </summary>
    ''' <param name="iDUSUARIO">Initial value of the IDUSUARIO property.</param>
    ''' <param name="uSUARIO">Initial value of the USUARIO property.</param>
    Public Shared Function CreateUSUARIOS(iDUSUARIO As Global.System.Decimal, uSUARIO As Global.System.String) As USUARIOS
        Dim uSUARIOS as USUARIOS = New USUARIOS
        uSUARIOS.IDUSUARIO = iDUSUARIO
        uSUARIOS.USUARIO = uSUARIO
        Return uSUARIOS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDUSUARIO() As Global.System.Decimal
        Get
            Return _IDUSUARIO
        End Get
        Set
            If (_IDUSUARIO <> Value) Then
                OnIDUSUARIOChanging(value)
                ReportPropertyChanging("IDUSUARIO")
                _IDUSUARIO = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDUSUARIO")
                OnIDUSUARIOChanged()
            End If
        End Set
    End Property

    Private _IDUSUARIO As Global.System.Decimal
    Private Partial Sub OnIDUSUARIOChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDUSUARIOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property USUARIO() As Global.System.String
        Get
            Return _USUARIO
        End Get
        Set
            OnUSUARIOChanging(value)
            ReportPropertyChanging("USUARIO")
            _USUARIO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("USUARIO")
            OnUSUARIOChanged()
        End Set
    End Property

    Private _USUARIO As Global.System.String
    Private Partial Sub OnUSUARIOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUSUARIOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CONTRASENA() As Global.System.String
        Get
            Return _CONTRASENA
        End Get
        Set
            OnCONTRASENAChanging(value)
            ReportPropertyChanging("CONTRASENA")
            _CONTRASENA = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CONTRASENA")
            OnCONTRASENAChanged()
        End Set
    End Property

    Private _CONTRASENA As Global.System.String
    Private Partial Sub OnCONTRASENAChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCONTRASENAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            OnNOMBREChanging(value)
            ReportPropertyChanging("NOMBRE")
            _NOMBRE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE")
            OnNOMBREChanged()
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property APELLIDOS() As Global.System.String
        Get
            Return _APELLIDOS
        End Get
        Set
            OnAPELLIDOSChanging(value)
            ReportPropertyChanging("APELLIDOS")
            _APELLIDOS = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("APELLIDOS")
            OnAPELLIDOSChanged()
        End Set
    End Property

    Private _APELLIDOS As Global.System.String
    Private Partial Sub OnAPELLIDOSChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAPELLIDOSChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ESTADO() As Nullable(Of Global.System.Decimal)
        Get
            Return _ESTADO
        End Get
        Set
            OnESTADOChanging(value)
            ReportPropertyChanging("ESTADO")
            _ESTADO = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ESTADO")
            OnESTADOChanged()
        End Set
    End Property

    Private _ESTADO As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnESTADOChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnESTADOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_SUCURSAL_OFICINA() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDDETALLE_SUCURSAL_OFICINA
        End Get
        Set
            OnIDDETALLE_SUCURSAL_OFICINAChanging(value)
            ReportPropertyChanging("IDDETALLE_SUCURSAL_OFICINA")
            _IDDETALLE_SUCURSAL_OFICINA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDDETALLE_SUCURSAL_OFICINA")
            OnIDDETALLE_SUCURSAL_OFICINAChanged()
        End Set
    End Property

    Private _IDDETALLE_SUCURSAL_OFICINA As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA")>
    Public Property DETALLE_SUCURSAL_OFICINA() As DETALLE_SUCURSAL_OFICINA
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property DETALLE_SUCURSAL_OFICINAReference() As EntityReference(Of DETALLE_SUCURSAL_OFICINA)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "DETALLE_USUARIOS_PERFILES", "PERFILES")>
     Public Property PERFILES() As EntityCollection(Of PERFILES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of PERFILES)("ModeloTablas.DETALLE_USUARIOS_PERFILES", "PERFILES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of PERFILES)("ModeloTablas.DETALLE_USUARIOS_PERFILES", "PERFILES", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloTablas", Name:="VENTANILLAS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class VENTANILLAS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new VENTANILLAS object.
    ''' </summary>
    ''' <param name="iDVENTANILLA">Initial value of the IDVENTANILLA property.</param>
    ''' <param name="iDDETALLE_SUCURSAL_OFICINA">Initial value of the IDDETALLE_SUCURSAL_OFICINA property.</param>
    ''' <param name="nUMERO_VENTANILLA">Initial value of the NUMERO_VENTANILLA property.</param>
    Public Shared Function CreateVENTANILLAS(iDVENTANILLA As Global.System.Decimal, iDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal, nUMERO_VENTANILLA As Global.System.Decimal) As VENTANILLAS
        Dim vENTANILLAS as VENTANILLAS = New VENTANILLAS
        vENTANILLAS.IDVENTANILLA = iDVENTANILLA
        vENTANILLAS.IDDETALLE_SUCURSAL_OFICINA = iDDETALLE_SUCURSAL_OFICINA
        vENTANILLAS.NUMERO_VENTANILLA = nUMERO_VENTANILLA
        Return vENTANILLAS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDVENTANILLA() As Global.System.Decimal
        Get
            Return _IDVENTANILLA
        End Get
        Set
            If (_IDVENTANILLA <> Value) Then
                OnIDVENTANILLAChanging(value)
                ReportPropertyChanging("IDVENTANILLA")
                _IDVENTANILLA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDVENTANILLA")
                OnIDVENTANILLAChanged()
            End If
        End Set
    End Property

    Private _IDVENTANILLA As Global.System.Decimal
    Private Partial Sub OnIDVENTANILLAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDVENTANILLAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_SUCURSAL_OFICINA() As Global.System.Decimal
        Get
            Return _IDDETALLE_SUCURSAL_OFICINA
        End Get
        Set
            OnIDDETALLE_SUCURSAL_OFICINAChanging(value)
            ReportPropertyChanging("IDDETALLE_SUCURSAL_OFICINA")
            _IDDETALLE_SUCURSAL_OFICINA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDDETALLE_SUCURSAL_OFICINA")
            OnIDDETALLE_SUCURSAL_OFICINAChanged()
        End Set
    End Property

    Private _IDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NUMERO_VENTANILLA() As Global.System.Decimal
        Get
            Return _NUMERO_VENTANILLA
        End Get
        Set
            OnNUMERO_VENTANILLAChanging(value)
            ReportPropertyChanging("NUMERO_VENTANILLA")
            _NUMERO_VENTANILLA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("NUMERO_VENTANILLA")
            OnNUMERO_VENTANILLAChanged()
        End Set
    End Property

    Private _NUMERO_VENTANILLA As Global.System.Decimal
    Private Partial Sub OnNUMERO_VENTANILLAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnNUMERO_VENTANILLAChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA")>
    Public Property DETALLE_SUCURSAL_OFICINA() As DETALLE_SUCURSAL_OFICINA
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property DETALLE_SUCURSAL_OFICINAReference() As EntityReference(Of DETALLE_SUCURSAL_OFICINA)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("ModeloTablas.VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("ModeloTablas", "GESTIONES_VENTANILLAS", "DETALLE_OFICINA_GESTIONES")>
     Public Property DETALLE_OFICINA_GESTIONES() As EntityCollection(Of DETALLE_OFICINA_GESTIONES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("ModeloTablas.GESTIONES_VENTANILLAS", "DETALLE_OFICINA_GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("ModeloTablas.GESTIONES_VENTANILLAS", "DETALLE_OFICINA_GESTIONES", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


