
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("8a92190a-4fea-49fd-a8c7-1d77e5d17567")>
#Region "Contextos"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
Public Partial Class EntidadesInsert
    Inherits ObjectContext

    #Region "Constructores"

    ''' <summary>
    ''' Inicializa un nuevo objeto EntidadesInsert usando la cadena de conexión encontrada en la sección 'EntidadesInsert' del archivo de configuración de la aplicación.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=EntidadesInsert", "EntidadesInsert")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto EntidadesInsert.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "EntidadesInsert")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto EntidadesInsert.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "EntidadesInsert")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Métodos parciales"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propiedades de ObjectSet"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property GESTIONES_VENTANILLAS() As ObjectSet(Of GESTIONES_VENTANILLAS)
        Get
            If (_GESTIONES_VENTANILLAS Is Nothing) Then
                _GESTIONES_VENTANILLAS = MyBase.CreateObjectSet(Of GESTIONES_VENTANILLAS)("GESTIONES_VENTANILLAS")
            End If
            Return _GESTIONES_VENTANILLAS
        End Get
    End Property

    Private _GESTIONES_VENTANILLAS As ObjectSet(Of GESTIONES_VENTANILLAS)

    #End Region

    #Region "Métodos AddTo"

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet GESTIONES_VENTANILLAS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToGESTIONES_VENTANILLAS(ByVal gESTIONES_VENTANILLAS As GESTIONES_VENTANILLAS)
        MyBase.AddObject("GESTIONES_VENTANILLAS", gESTIONES_VENTANILLAS)
    End Sub

    #End Region

End Class

#End Region

#Region "Entidades"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloGestionesVentanillas", Name:="GESTIONES_VENTANILLAS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class GESTIONES_VENTANILLAS
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto GESTIONES_VENTANILLAS.
    ''' </summary>
    ''' <param name="iDVENTANILLA">Valor inicial de la propiedad IDVENTANILLA.</param>
    ''' <param name="iDDETALLE_GESTION_OFICINA">Valor inicial de la propiedad IDDETALLE_GESTION_OFICINA.</param>
    Public Shared Function CreateGESTIONES_VENTANILLAS(iDVENTANILLA As Global.System.Decimal, iDDETALLE_GESTION_OFICINA As Global.System.Decimal) As GESTIONES_VENTANILLAS
        Dim gESTIONES_VENTANILLAS as GESTIONES_VENTANILLAS = New GESTIONES_VENTANILLAS
        gESTIONES_VENTANILLAS.IDVENTANILLA = iDVENTANILLA
        gESTIONES_VENTANILLAS.IDDETALLE_GESTION_OFICINA = iDDETALLE_GESTION_OFICINA
        Return gESTIONES_VENTANILLAS
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDVENTANILLA() As Global.System.Decimal
        Get
            Return _IDVENTANILLA
        End Get
        Set
            If (_IDVENTANILLA <> Value) Then
                OnIDVENTANILLAChanging(value)
                ReportPropertyChanging("IDVENTANILLA")
                _IDVENTANILLA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDVENTANILLA")
                OnIDVENTANILLAChanged()
            End If
        End Set
    End Property

    Private _IDVENTANILLA As Global.System.Decimal
    Private Partial Sub OnIDVENTANILLAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDVENTANILLAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_GESTION_OFICINA() As Global.System.Decimal
        Get
            Return _IDDETALLE_GESTION_OFICINA
        End Get
        Set
            If (_IDDETALLE_GESTION_OFICINA <> Value) Then
                OnIDDETALLE_GESTION_OFICINAChanging(value)
                ReportPropertyChanging("IDDETALLE_GESTION_OFICINA")
                _IDDETALLE_GESTION_OFICINA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDDETALLE_GESTION_OFICINA")
                OnIDDETALLE_GESTION_OFICINAChanged()
            End If
        End Set
    End Property

    Private _IDDETALLE_GESTION_OFICINA As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_GESTION_OFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_GESTION_OFICINAChanged()
    End Sub

    #End Region

End Class

#End Region


