
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("78555ad2-f363-4c6a-8fbb-b3f0640aa103")>
#Region "Contextos"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
Public Partial Class EntidadesVistas
    Inherits ObjectContext

    #Region "Constructores"

    ''' <summary>
    ''' Inicializa un nuevo objeto EntidadesVistas usando la cadena de conexión encontrada en la sección 'EntidadesVistas' del archivo de configuración de la aplicación.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=EntidadesVistas", "EntidadesVistas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto EntidadesVistas.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "EntidadesVistas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto EntidadesVistas.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "EntidadesVistas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Métodos parciales"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propiedades de ObjectSet"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property ATENCION_X_OFICINAConjunto() As ObjectSet(Of ATENCION_X_OFICINA)
        Get
            If (_ATENCION_X_OFICINAConjunto Is Nothing) Then
                _ATENCION_X_OFICINAConjunto = MyBase.CreateObjectSet(Of ATENCION_X_OFICINA)("ATENCION_X_OFICINAConjunto")
            End If
            Return _ATENCION_X_OFICINAConjunto
        End Get
    End Property

    Private _ATENCION_X_OFICINAConjunto As ObjectSet(Of ATENCION_X_OFICINA)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property COMODIN() As ObjectSet(Of COMODIN)
        Get
            If (_COMODIN Is Nothing) Then
                _COMODIN = MyBase.CreateObjectSet(Of COMODIN)("COMODIN")
            End If
            Return _COMODIN
        End Get
    End Property

    Private _COMODIN As ObjectSet(Of COMODIN)

    #End Region

    #Region "Métodos AddTo"

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet ATENCION_X_OFICINAConjunto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToATENCION_X_OFICINAConjunto(ByVal aTENCION_X_OFICINA As ATENCION_X_OFICINA)
        MyBase.AddObject("ATENCION_X_OFICINAConjunto", aTENCION_X_OFICINA)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet COMODIN. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToCOMODIN(ByVal cOMODIN As COMODIN)
        MyBase.AddObject("COMODIN", cOMODIN)
    End Sub

    #End Region

    #Region "Importaciones de funciones"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    ''' <param name="vIDDETALLE_SUCURSAL_OFICINA">No hay documentación de metadatos disponible.</param>
    ''' <param name="dESDE">No hay documentación de metadatos disponible.</param>
    ''' <param name="hASTA">No hay documentación de metadatos disponible.</param>
    Public Function SP_RTE_ATENCIONXOFICINA(vIDDETALLE_SUCURSAL_OFICINA As Nullable(Of Global.System.Decimal), dESDE As Global.System.String, hASTA As Global.System.String) As Integer
        Dim vIDDETALLE_SUCURSAL_OFICINAParameter As ObjectParameter
        If (vIDDETALLE_SUCURSAL_OFICINA.HasValue)
            vIDDETALLE_SUCURSAL_OFICINAParameter = New ObjectParameter("VIDDETALLE_SUCURSAL_OFICINA", vIDDETALLE_SUCURSAL_OFICINA)
        Else
            vIDDETALLE_SUCURSAL_OFICINAParameter = New ObjectParameter("VIDDETALLE_SUCURSAL_OFICINA", GetType(Global.System.Decimal))
        End If

        Dim dESDEParameter As ObjectParameter
        If (dESDE IsNot Nothing)
            dESDEParameter = New ObjectParameter("DESDE", dESDE)
        Else
            dESDEParameter = New ObjectParameter("DESDE", GetType(Global.System.String))
        End If

        Dim hASTAParameter As ObjectParameter
        If (hASTA IsNot Nothing)
            hASTAParameter = New ObjectParameter("HASTA", hASTA)
        Else
            hASTAParameter = New ObjectParameter("HASTA", GetType(Global.System.String))
        End If

        Return MyBase.ExecuteFunction("SP_RTE_ATENCIONXOFICINA", vIDDETALLE_SUCURSAL_OFICINAParameter, dESDEParameter, hASTAParameter)

    End Function

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    ''' <param name="vIDDETALLE_SUCURSAL_OFICINA">No hay documentación de metadatos disponible.</param>
    ''' <param name="dESDE">No hay documentación de metadatos disponible.</param>
    ''' <param name="hASTA">No hay documentación de metadatos disponible.</param>
    Public Function SP_RTE_ATENCIONXOFICINA1(vIDDETALLE_SUCURSAL_OFICINA As Nullable(Of Global.System.Decimal), dESDE As Global.System.String, hASTA As Global.System.String) As ObjectResult(Of ATENCION_X_OFICINA)
        Dim vIDDETALLE_SUCURSAL_OFICINAParameter As ObjectParameter
        If (vIDDETALLE_SUCURSAL_OFICINA.HasValue)
            vIDDETALLE_SUCURSAL_OFICINAParameter = New ObjectParameter("VIDDETALLE_SUCURSAL_OFICINA", vIDDETALLE_SUCURSAL_OFICINA)
        Else
            vIDDETALLE_SUCURSAL_OFICINAParameter = New ObjectParameter("VIDDETALLE_SUCURSAL_OFICINA", GetType(Global.System.Decimal))
        End If

        Dim dESDEParameter As ObjectParameter
        If (dESDE IsNot Nothing)
            dESDEParameter = New ObjectParameter("DESDE", dESDE)
        Else
            dESDEParameter = New ObjectParameter("DESDE", GetType(Global.System.String))
        End If

        Dim hASTAParameter As ObjectParameter
        If (hASTA IsNot Nothing)
            hASTAParameter = New ObjectParameter("HASTA", hASTA)
        Else
            hASTAParameter = New ObjectParameter("HASTA", GetType(Global.System.String))
        End If

        Return MyBase.ExecuteFunction(Of ATENCION_X_OFICINA)("SP_RTE_ATENCIONXOFICINA1", vIDDETALLE_SUCURSAL_OFICINAParameter, dESDEParameter, hASTAParameter)

    End Function
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    ''' <param name="mergeOption"></param>
    ''' <param name="vIDDETALLE_SUCURSAL_OFICINA">No hay documentación de metadatos disponible.</param>
    ''' <param name="dESDE">No hay documentación de metadatos disponible.</param>
    ''' <param name="hASTA">No hay documentación de metadatos disponible.</param>
    Public Function SP_RTE_ATENCIONXOFICINA1(vIDDETALLE_SUCURSAL_OFICINA As Nullable(Of Global.System.Decimal), dESDE As Global.System.String, hASTA As Global.System.String, mergeOption As MergeOption) As ObjectResult(Of ATENCION_X_OFICINA)
        Dim vIDDETALLE_SUCURSAL_OFICINAParameter As ObjectParameter
        If (vIDDETALLE_SUCURSAL_OFICINA.HasValue)
            vIDDETALLE_SUCURSAL_OFICINAParameter = New ObjectParameter("VIDDETALLE_SUCURSAL_OFICINA", vIDDETALLE_SUCURSAL_OFICINA)
        Else
            vIDDETALLE_SUCURSAL_OFICINAParameter = New ObjectParameter("VIDDETALLE_SUCURSAL_OFICINA", GetType(Global.System.Decimal))
        End If

        Dim dESDEParameter As ObjectParameter
        If (dESDE IsNot Nothing)
            dESDEParameter = New ObjectParameter("DESDE", dESDE)
        Else
            dESDEParameter = New ObjectParameter("DESDE", GetType(Global.System.String))
        End If

        Dim hASTAParameter As ObjectParameter
        If (hASTA IsNot Nothing)
            hASTAParameter = New ObjectParameter("HASTA", hASTA)
        Else
            hASTAParameter = New ObjectParameter("HASTA", GetType(Global.System.String))
        End If

        Return MyBase.ExecuteFunction(Of ATENCION_X_OFICINA)("SP_RTE_ATENCIONXOFICINA1", mergeOption, vIDDETALLE_SUCURSAL_OFICINAParameter, dESDEParameter, hASTAParameter)

    End Function

    #End Region

End Class

#End Region

#Region "Entidades"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloVistas", Name:="ATENCION_X_OFICINA")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ATENCION_X_OFICINA
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto ATENCION_X_OFICINA.
    ''' </summary>
    ''' <param name="nUMFILA">Valor inicial de la propiedad NUMFILA.</param>
    ''' <param name="dEPARTAMENTO">Valor inicial de la propiedad DEPARTAMENTO.</param>
    ''' <param name="mUNICIPIO">Valor inicial de la propiedad MUNICIPIO.</param>
    ''' <param name="sUCURSAL">Valor inicial de la propiedad SUCURSAL.</param>
    ''' <param name="oFICINA">Valor inicial de la propiedad OFICINA.</param>
    ''' <param name="nOMBRE_EMPLEADO">Valor inicial de la propiedad NOMBRE_EMPLEADO.</param>
    ''' <param name="gESTION">Valor inicial de la propiedad GESTION.</param>
    ''' <param name="gESTIONES_ATENDIDAS">Valor inicial de la propiedad GESTIONES_ATENDIDAS.</param>
    ''' <param name="pROMEDIO_ESPERA">Valor inicial de la propiedad PROMEDIO_ESPERA.</param>
    ''' <param name="pROMEDIO_ATENCION">Valor inicial de la propiedad PROMEDIO_ATENCION.</param>
    Public Shared Function CreateATENCION_X_OFICINA(nUMFILA As Global.System.Int32, dEPARTAMENTO As Global.System.String, mUNICIPIO As Global.System.String, sUCURSAL As Global.System.String, oFICINA As Global.System.String, nOMBRE_EMPLEADO As Global.System.String, gESTION As Global.System.String, gESTIONES_ATENDIDAS As Global.System.Int32, pROMEDIO_ESPERA As Global.System.Decimal, pROMEDIO_ATENCION As Global.System.Decimal) As ATENCION_X_OFICINA
        Dim aTENCION_X_OFICINA as ATENCION_X_OFICINA = New ATENCION_X_OFICINA
        aTENCION_X_OFICINA.NUMFILA = nUMFILA
        aTENCION_X_OFICINA.DEPARTAMENTO = dEPARTAMENTO
        aTENCION_X_OFICINA.MUNICIPIO = mUNICIPIO
        aTENCION_X_OFICINA.SUCURSAL = sUCURSAL
        aTENCION_X_OFICINA.OFICINA = oFICINA
        aTENCION_X_OFICINA.NOMBRE_EMPLEADO = nOMBRE_EMPLEADO
        aTENCION_X_OFICINA.GESTION = gESTION
        aTENCION_X_OFICINA.GESTIONES_ATENDIDAS = gESTIONES_ATENDIDAS
        aTENCION_X_OFICINA.PROMEDIO_ESPERA = pROMEDIO_ESPERA
        aTENCION_X_OFICINA.PROMEDIO_ATENCION = pROMEDIO_ATENCION
        Return aTENCION_X_OFICINA
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NUMFILA() As Global.System.Int32
        Get
            Return _NUMFILA
        End Get
        Set
            If (_NUMFILA <> Value) Then
                OnNUMFILAChanging(value)
                ReportPropertyChanging("NUMFILA")
                _NUMFILA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("NUMFILA")
                OnNUMFILAChanged()
            End If
        End Set
    End Property

    Private _NUMFILA As Global.System.Int32
    Private Partial Sub OnNUMFILAChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnNUMFILAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DEPARTAMENTO() As Global.System.String
        Get
            Return _DEPARTAMENTO
        End Get
        Set
            OnDEPARTAMENTOChanging(value)
            ReportPropertyChanging("DEPARTAMENTO")
            _DEPARTAMENTO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("DEPARTAMENTO")
            OnDEPARTAMENTOChanged()
        End Set
    End Property

    Private _DEPARTAMENTO As Global.System.String
    Private Partial Sub OnDEPARTAMENTOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDEPARTAMENTOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MUNICIPIO() As Global.System.String
        Get
            Return _MUNICIPIO
        End Get
        Set
            OnMUNICIPIOChanging(value)
            ReportPropertyChanging("MUNICIPIO")
            _MUNICIPIO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("MUNICIPIO")
            OnMUNICIPIOChanged()
        End Set
    End Property

    Private _MUNICIPIO As Global.System.String
    Private Partial Sub OnMUNICIPIOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMUNICIPIOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SUCURSAL() As Global.System.String
        Get
            Return _SUCURSAL
        End Get
        Set
            OnSUCURSALChanging(value)
            ReportPropertyChanging("SUCURSAL")
            _SUCURSAL = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("SUCURSAL")
            OnSUCURSALChanged()
        End Set
    End Property

    Private _SUCURSAL As Global.System.String
    Private Partial Sub OnSUCURSALChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSUCURSALChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OFICINA() As Global.System.String
        Get
            Return _OFICINA
        End Get
        Set
            OnOFICINAChanging(value)
            ReportPropertyChanging("OFICINA")
            _OFICINA = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("OFICINA")
            OnOFICINAChanged()
        End Set
    End Property

    Private _OFICINA As Global.System.String
    Private Partial Sub OnOFICINAChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnOFICINAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NOMBRE_EMPLEADO() As Global.System.String
        Get
            Return _NOMBRE_EMPLEADO
        End Get
        Set
            OnNOMBRE_EMPLEADOChanging(value)
            ReportPropertyChanging("NOMBRE_EMPLEADO")
            _NOMBRE_EMPLEADO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NOMBRE_EMPLEADO")
            OnNOMBRE_EMPLEADOChanged()
        End Set
    End Property

    Private _NOMBRE_EMPLEADO As Global.System.String
    Private Partial Sub OnNOMBRE_EMPLEADOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_EMPLEADOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property GESTION() As Global.System.String
        Get
            Return _GESTION
        End Get
        Set
            OnGESTIONChanging(value)
            ReportPropertyChanging("GESTION")
            _GESTION = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("GESTION")
            OnGESTIONChanged()
        End Set
    End Property

    Private _GESTION As Global.System.String
    Private Partial Sub OnGESTIONChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnGESTIONChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property GESTIONES_ATENDIDAS() As Global.System.Int32
        Get
            Return _GESTIONES_ATENDIDAS
        End Get
        Set
            OnGESTIONES_ATENDIDASChanging(value)
            ReportPropertyChanging("GESTIONES_ATENDIDAS")
            _GESTIONES_ATENDIDAS = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("GESTIONES_ATENDIDAS")
            OnGESTIONES_ATENDIDASChanged()
        End Set
    End Property

    Private _GESTIONES_ATENDIDAS As Global.System.Int32
    Private Partial Sub OnGESTIONES_ATENDIDASChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnGESTIONES_ATENDIDASChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PROMEDIO_ESPERA() As Global.System.Decimal
        Get
            Return _PROMEDIO_ESPERA
        End Get
        Set
            OnPROMEDIO_ESPERAChanging(value)
            ReportPropertyChanging("PROMEDIO_ESPERA")
            _PROMEDIO_ESPERA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PROMEDIO_ESPERA")
            OnPROMEDIO_ESPERAChanged()
        End Set
    End Property

    Private _PROMEDIO_ESPERA As Global.System.Decimal
    Private Partial Sub OnPROMEDIO_ESPERAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnPROMEDIO_ESPERAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PROMEDIO_ATENCION() As Global.System.Decimal
        Get
            Return _PROMEDIO_ATENCION
        End Get
        Set
            OnPROMEDIO_ATENCIONChanging(value)
            ReportPropertyChanging("PROMEDIO_ATENCION")
            _PROMEDIO_ATENCION = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PROMEDIO_ATENCION")
            OnPROMEDIO_ATENCIONChanged()
        End Set
    End Property

    Private _PROMEDIO_ATENCION As Global.System.Decimal
    Private Partial Sub OnPROMEDIO_ATENCIONChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnPROMEDIO_ATENCIONChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloVistas", Name:="COMODIN")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class COMODIN
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto COMODIN.
    ''' </summary>
    ''' <param name="iDCOMODIN">Valor inicial de la propiedad IDCOMODIN.</param>
    Public Shared Function CreateCOMODIN(iDCOMODIN As Global.System.String) As COMODIN
        Dim cOMODIN as COMODIN = New COMODIN
        cOMODIN.IDCOMODIN = iDCOMODIN
        Return cOMODIN
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDCOMODIN() As Global.System.String
        Get
            Return _IDCOMODIN
        End Get
        Set
            If (_IDCOMODIN <> Value) Then
                OnIDCOMODINChanging(value)
                ReportPropertyChanging("IDCOMODIN")
                _IDCOMODIN = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("IDCOMODIN")
                OnIDCOMODINChanged()
            End If
        End Set
    End Property

    Private _IDCOMODIN As Global.System.String
    Private Partial Sub OnIDCOMODINChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIDCOMODINChanged()
    End Sub

    #End Region

End Class

#End Region


