
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("95e2e65d-62e8-4dbb-9c7f-cfd4971b497f")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class EntidadesVistas
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new EntidadesVistas object using the connection string found in the 'EntidadesVistas' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=EntidadesVistas", "EntidadesVistas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new EntidadesVistas object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "EntidadesVistas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new EntidadesVistas object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "EntidadesVistas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property ATENCION_X_OFICINAConjunto() As ObjectSet(Of ATENCION_X_OFICINA)
        Get
            If (_ATENCION_X_OFICINAConjunto Is Nothing) Then
                _ATENCION_X_OFICINAConjunto = MyBase.CreateObjectSet(Of ATENCION_X_OFICINA)("ATENCION_X_OFICINAConjunto")
            End If
            Return _ATENCION_X_OFICINAConjunto
        End Get
    End Property

    Private _ATENCION_X_OFICINAConjunto As ObjectSet(Of ATENCION_X_OFICINA)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property COMODIN() As ObjectSet(Of COMODIN)
        Get
            If (_COMODIN Is Nothing) Then
                _COMODIN = MyBase.CreateObjectSet(Of COMODIN)("COMODIN")
            End If
            Return _COMODIN
        End Get
    End Property

    Private _COMODIN As ObjectSet(Of COMODIN)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property V_ATENCIONXOFICINA() As ObjectSet(Of V_ATENCIONXOFICINA)
        Get
            If (_V_ATENCIONXOFICINA Is Nothing) Then
                _V_ATENCIONXOFICINA = MyBase.CreateObjectSet(Of V_ATENCIONXOFICINA)("V_ATENCIONXOFICINA")
            End If
            Return _V_ATENCIONXOFICINA
        End Get
    End Property

    Private _V_ATENCIONXOFICINA As ObjectSet(Of V_ATENCIONXOFICINA)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property TRAMITES_RECIBIDOSConjunto() As ObjectSet(Of TRAMITES_RECIBIDOS)
        Get
            If (_TRAMITES_RECIBIDOSConjunto Is Nothing) Then
                _TRAMITES_RECIBIDOSConjunto = MyBase.CreateObjectSet(Of TRAMITES_RECIBIDOS)("TRAMITES_RECIBIDOSConjunto")
            End If
            Return _TRAMITES_RECIBIDOSConjunto
        End Get
    End Property

    Private _TRAMITES_RECIBIDOSConjunto As ObjectSet(Of TRAMITES_RECIBIDOS)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property TRAMITES_ENTREGADOSConjunto() As ObjectSet(Of TRAMITES_ENTREGADOS)
        Get
            If (_TRAMITES_ENTREGADOSConjunto Is Nothing) Then
                _TRAMITES_ENTREGADOSConjunto = MyBase.CreateObjectSet(Of TRAMITES_ENTREGADOS)("TRAMITES_ENTREGADOSConjunto")
            End If
            Return _TRAMITES_ENTREGADOSConjunto
        End Get
    End Property

    Private _TRAMITES_ENTREGADOSConjunto As ObjectSet(Of TRAMITES_ENTREGADOS)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the ATENCION_X_OFICINAConjunto EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToATENCION_X_OFICINAConjunto(ByVal aTENCION_X_OFICINA As ATENCION_X_OFICINA)
        MyBase.AddObject("ATENCION_X_OFICINAConjunto", aTENCION_X_OFICINA)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the COMODIN EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCOMODIN(ByVal cOMODIN As COMODIN)
        MyBase.AddObject("COMODIN", cOMODIN)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the V_ATENCIONXOFICINA EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToV_ATENCIONXOFICINA(ByVal v_ATENCIONXOFICINA As V_ATENCIONXOFICINA)
        MyBase.AddObject("V_ATENCIONXOFICINA", v_ATENCIONXOFICINA)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the TRAMITES_RECIBIDOSConjunto EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTRAMITES_RECIBIDOSConjunto(ByVal tRAMITES_RECIBIDOS As TRAMITES_RECIBIDOS)
        MyBase.AddObject("TRAMITES_RECIBIDOSConjunto", tRAMITES_RECIBIDOS)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the TRAMITES_ENTREGADOSConjunto EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTRAMITES_ENTREGADOSConjunto(ByVal tRAMITES_ENTREGADOS As TRAMITES_ENTREGADOS)
        MyBase.AddObject("TRAMITES_ENTREGADOSConjunto", tRAMITES_ENTREGADOS)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloVistas", Name:="ATENCION_X_OFICINA")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class ATENCION_X_OFICINA
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new ATENCION_X_OFICINA object.
    ''' </summary>
    ''' <param name="nUMFILA">Initial value of the NUMFILA property.</param>
    ''' <param name="dEPARTAMENTO">Initial value of the DEPARTAMENTO property.</param>
    ''' <param name="mUNICIPIO">Initial value of the MUNICIPIO property.</param>
    ''' <param name="sUCURSAL">Initial value of the SUCURSAL property.</param>
    ''' <param name="oFICINA">Initial value of the OFICINA property.</param>
    ''' <param name="nOMBRE_EMPLEADO">Initial value of the NOMBRE_EMPLEADO property.</param>
    ''' <param name="gESTION">Initial value of the GESTION property.</param>
    ''' <param name="gESTIONES_ATENDIDAS">Initial value of the GESTIONES_ATENDIDAS property.</param>
    Public Shared Function CreateATENCION_X_OFICINA(nUMFILA As Global.System.Int32, dEPARTAMENTO As Global.System.String, mUNICIPIO As Global.System.String, sUCURSAL As Global.System.String, oFICINA As Global.System.String, nOMBRE_EMPLEADO As Global.System.String, gESTION As Global.System.String, gESTIONES_ATENDIDAS As Global.System.Int32) As ATENCION_X_OFICINA
        Dim aTENCION_X_OFICINA as ATENCION_X_OFICINA = New ATENCION_X_OFICINA
        aTENCION_X_OFICINA.NUMFILA = nUMFILA
        aTENCION_X_OFICINA.DEPARTAMENTO = dEPARTAMENTO
        aTENCION_X_OFICINA.MUNICIPIO = mUNICIPIO
        aTENCION_X_OFICINA.SUCURSAL = sUCURSAL
        aTENCION_X_OFICINA.OFICINA = oFICINA
        aTENCION_X_OFICINA.NOMBRE_EMPLEADO = nOMBRE_EMPLEADO
        aTENCION_X_OFICINA.GESTION = gESTION
        aTENCION_X_OFICINA.GESTIONES_ATENDIDAS = gESTIONES_ATENDIDAS
        Return aTENCION_X_OFICINA
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NUMFILA() As Global.System.Int32
        Get
            Return _NUMFILA
        End Get
        Set
            If (_NUMFILA <> Value) Then
                OnNUMFILAChanging(value)
                ReportPropertyChanging("NUMFILA")
                _NUMFILA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("NUMFILA")
                OnNUMFILAChanged()
            End If
        End Set
    End Property

    Private _NUMFILA As Global.System.Int32
    Private Partial Sub OnNUMFILAChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnNUMFILAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DEPARTAMENTO() As Global.System.String
        Get
            Return _DEPARTAMENTO
        End Get
        Set
            OnDEPARTAMENTOChanging(value)
            ReportPropertyChanging("DEPARTAMENTO")
            _DEPARTAMENTO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("DEPARTAMENTO")
            OnDEPARTAMENTOChanged()
        End Set
    End Property

    Private _DEPARTAMENTO As Global.System.String
    Private Partial Sub OnDEPARTAMENTOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDEPARTAMENTOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MUNICIPIO() As Global.System.String
        Get
            Return _MUNICIPIO
        End Get
        Set
            OnMUNICIPIOChanging(value)
            ReportPropertyChanging("MUNICIPIO")
            _MUNICIPIO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("MUNICIPIO")
            OnMUNICIPIOChanged()
        End Set
    End Property

    Private _MUNICIPIO As Global.System.String
    Private Partial Sub OnMUNICIPIOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMUNICIPIOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SUCURSAL() As Global.System.String
        Get
            Return _SUCURSAL
        End Get
        Set
            OnSUCURSALChanging(value)
            ReportPropertyChanging("SUCURSAL")
            _SUCURSAL = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("SUCURSAL")
            OnSUCURSALChanged()
        End Set
    End Property

    Private _SUCURSAL As Global.System.String
    Private Partial Sub OnSUCURSALChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSUCURSALChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OFICINA() As Global.System.String
        Get
            Return _OFICINA
        End Get
        Set
            OnOFICINAChanging(value)
            ReportPropertyChanging("OFICINA")
            _OFICINA = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("OFICINA")
            OnOFICINAChanged()
        End Set
    End Property

    Private _OFICINA As Global.System.String
    Private Partial Sub OnOFICINAChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnOFICINAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NOMBRE_EMPLEADO() As Global.System.String
        Get
            Return _NOMBRE_EMPLEADO
        End Get
        Set
            OnNOMBRE_EMPLEADOChanging(value)
            ReportPropertyChanging("NOMBRE_EMPLEADO")
            _NOMBRE_EMPLEADO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NOMBRE_EMPLEADO")
            OnNOMBRE_EMPLEADOChanged()
        End Set
    End Property

    Private _NOMBRE_EMPLEADO As Global.System.String
    Private Partial Sub OnNOMBRE_EMPLEADOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_EMPLEADOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property GESTION() As Global.System.String
        Get
            Return _GESTION
        End Get
        Set
            OnGESTIONChanging(value)
            ReportPropertyChanging("GESTION")
            _GESTION = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("GESTION")
            OnGESTIONChanged()
        End Set
    End Property

    Private _GESTION As Global.System.String
    Private Partial Sub OnGESTIONChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnGESTIONChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property GESTIONES_ATENDIDAS() As Global.System.Int32
        Get
            Return _GESTIONES_ATENDIDAS
        End Get
        Set
            OnGESTIONES_ATENDIDASChanging(value)
            ReportPropertyChanging("GESTIONES_ATENDIDAS")
            _GESTIONES_ATENDIDAS = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("GESTIONES_ATENDIDAS")
            OnGESTIONES_ATENDIDASChanged()
        End Set
    End Property

    Private _GESTIONES_ATENDIDAS As Global.System.Int32
    Private Partial Sub OnGESTIONES_ATENDIDASChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnGESTIONES_ATENDIDASChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PROMEDIO_ESPERA() As Nullable(Of Global.System.Decimal)
        Get
            Return _PROMEDIO_ESPERA
        End Get
        Set
            OnPROMEDIO_ESPERAChanging(value)
            ReportPropertyChanging("PROMEDIO_ESPERA")
            _PROMEDIO_ESPERA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PROMEDIO_ESPERA")
            OnPROMEDIO_ESPERAChanged()
        End Set
    End Property

    Private _PROMEDIO_ESPERA As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnPROMEDIO_ESPERAChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnPROMEDIO_ESPERAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PROMEDIO_ATENCION() As Nullable(Of Global.System.Decimal)
        Get
            Return _PROMEDIO_ATENCION
        End Get
        Set
            OnPROMEDIO_ATENCIONChanging(value)
            ReportPropertyChanging("PROMEDIO_ATENCION")
            _PROMEDIO_ATENCION = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PROMEDIO_ATENCION")
            OnPROMEDIO_ATENCIONChanged()
        End Set
    End Property

    Private _PROMEDIO_ATENCION As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnPROMEDIO_ATENCIONChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnPROMEDIO_ATENCIONChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloVistas", Name:="COMODIN")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class COMODIN
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new COMODIN object.
    ''' </summary>
    ''' <param name="iDCOMODIN">Initial value of the IDCOMODIN property.</param>
    Public Shared Function CreateCOMODIN(iDCOMODIN As Global.System.String) As COMODIN
        Dim cOMODIN as COMODIN = New COMODIN
        cOMODIN.IDCOMODIN = iDCOMODIN
        Return cOMODIN
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDCOMODIN() As Global.System.String
        Get
            Return _IDCOMODIN
        End Get
        Set
            If (_IDCOMODIN <> Value) Then
                OnIDCOMODINChanging(value)
                ReportPropertyChanging("IDCOMODIN")
                _IDCOMODIN = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("IDCOMODIN")
                OnIDCOMODINChanged()
            End If
        End Set
    End Property

    Private _IDCOMODIN As Global.System.String
    Private Partial Sub OnIDCOMODINChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIDCOMODINChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloVistas", Name:="TRAMITES_ENTREGADOS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class TRAMITES_ENTREGADOS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TRAMITES_ENTREGADOS object.
    ''' </summary>
    ''' <param name="nUMFILA">Initial value of the NUMFILA property.</param>
    ''' <param name="nUM_RECIBO">Initial value of the NUM_RECIBO property.</param>
    ''' <param name="mONTO_RECIBO">Initial value of the MONTO_RECIBO property.</param>
    ''' <param name="nOMBRE">Initial value of the NOMBRE property.</param>
    Public Shared Function CreateTRAMITES_ENTREGADOS(nUMFILA As Global.System.Int32, nUM_RECIBO As Global.System.String, mONTO_RECIBO As Global.System.String, nOMBRE As Global.System.String) As TRAMITES_ENTREGADOS
        Dim tRAMITES_ENTREGADOS as TRAMITES_ENTREGADOS = New TRAMITES_ENTREGADOS
        tRAMITES_ENTREGADOS.NUMFILA = nUMFILA
        tRAMITES_ENTREGADOS.NUM_RECIBO = nUM_RECIBO
        tRAMITES_ENTREGADOS.MONTO_RECIBO = mONTO_RECIBO
        tRAMITES_ENTREGADOS.NOMBRE = nOMBRE
        Return tRAMITES_ENTREGADOS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NUMFILA() As Global.System.Int32
        Get
            Return _NUMFILA
        End Get
        Set
            If (_NUMFILA <> Value) Then
                OnNUMFILAChanging(value)
                ReportPropertyChanging("NUMFILA")
                _NUMFILA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("NUMFILA")
                OnNUMFILAChanged()
            End If
        End Set
    End Property

    Private _NUMFILA As Global.System.Int32
    Private Partial Sub OnNUMFILAChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnNUMFILAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NUM_RECIBO() As Global.System.String
        Get
            Return _NUM_RECIBO
        End Get
        Set
            OnNUM_RECIBOChanging(value)
            ReportPropertyChanging("NUM_RECIBO")
            _NUM_RECIBO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NUM_RECIBO")
            OnNUM_RECIBOChanged()
        End Set
    End Property

    Private _NUM_RECIBO As Global.System.String
    Private Partial Sub OnNUM_RECIBOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNUM_RECIBOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MONTO_RECIBO() As Global.System.String
        Get
            Return _MONTO_RECIBO
        End Get
        Set
            OnMONTO_RECIBOChanging(value)
            ReportPropertyChanging("MONTO_RECIBO")
            _MONTO_RECIBO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("MONTO_RECIBO")
            OnMONTO_RECIBOChanged()
        End Set
    End Property

    Private _MONTO_RECIBO As Global.System.String
    Private Partial Sub OnMONTO_RECIBOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMONTO_RECIBOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            OnNOMBREChanging(value)
            ReportPropertyChanging("NOMBRE")
            _NOMBRE = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NOMBRE")
            OnNOMBREChanged()
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloVistas", Name:="TRAMITES_RECIBIDOS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class TRAMITES_RECIBIDOS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TRAMITES_RECIBIDOS object.
    ''' </summary>
    ''' <param name="nUMFILA">Initial value of the NUMFILA property.</param>
    ''' <param name="nUM_RECIBO">Initial value of the NUM_RECIBO property.</param>
    ''' <param name="mONTO_RECIBO">Initial value of the MONTO_RECIBO property.</param>
    ''' <param name="nUM_TRAMITES">Initial value of the NUM_TRAMITES property.</param>
    ''' <param name="nOMBRE">Initial value of the NOMBRE property.</param>
    Public Shared Function CreateTRAMITES_RECIBIDOS(nUMFILA As Global.System.Int32, nUM_RECIBO As Global.System.String, mONTO_RECIBO As Global.System.String, nUM_TRAMITES As Global.System.String, nOMBRE As Global.System.String) As TRAMITES_RECIBIDOS
        Dim tRAMITES_RECIBIDOS as TRAMITES_RECIBIDOS = New TRAMITES_RECIBIDOS
        tRAMITES_RECIBIDOS.NUMFILA = nUMFILA
        tRAMITES_RECIBIDOS.NUM_RECIBO = nUM_RECIBO
        tRAMITES_RECIBIDOS.MONTO_RECIBO = mONTO_RECIBO
        tRAMITES_RECIBIDOS.NUM_TRAMITES = nUM_TRAMITES
        tRAMITES_RECIBIDOS.NOMBRE = nOMBRE
        Return tRAMITES_RECIBIDOS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NUMFILA() As Global.System.Int32
        Get
            Return _NUMFILA
        End Get
        Set
            If (_NUMFILA <> Value) Then
                OnNUMFILAChanging(value)
                ReportPropertyChanging("NUMFILA")
                _NUMFILA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("NUMFILA")
                OnNUMFILAChanged()
            End If
        End Set
    End Property

    Private _NUMFILA As Global.System.Int32
    Private Partial Sub OnNUMFILAChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnNUMFILAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NUM_RECIBO() As Global.System.String
        Get
            Return _NUM_RECIBO
        End Get
        Set
            OnNUM_RECIBOChanging(value)
            ReportPropertyChanging("NUM_RECIBO")
            _NUM_RECIBO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NUM_RECIBO")
            OnNUM_RECIBOChanged()
        End Set
    End Property

    Private _NUM_RECIBO As Global.System.String
    Private Partial Sub OnNUM_RECIBOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNUM_RECIBOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property MONTO_RECIBO() As Global.System.String
        Get
            Return _MONTO_RECIBO
        End Get
        Set
            OnMONTO_RECIBOChanging(value)
            ReportPropertyChanging("MONTO_RECIBO")
            _MONTO_RECIBO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("MONTO_RECIBO")
            OnMONTO_RECIBOChanged()
        End Set
    End Property

    Private _MONTO_RECIBO As Global.System.String
    Private Partial Sub OnMONTO_RECIBOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMONTO_RECIBOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NUM_TRAMITES() As Global.System.String
        Get
            Return _NUM_TRAMITES
        End Get
        Set
            OnNUM_TRAMITESChanging(value)
            ReportPropertyChanging("NUM_TRAMITES")
            _NUM_TRAMITES = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NUM_TRAMITES")
            OnNUM_TRAMITESChanged()
        End Set
    End Property

    Private _NUM_TRAMITES As Global.System.String
    Private Partial Sub OnNUM_TRAMITESChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNUM_TRAMITESChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            OnNOMBREChanging(value)
            ReportPropertyChanging("NOMBRE")
            _NOMBRE = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NOMBRE")
            OnNOMBREChanged()
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloVistas", Name:="V_ATENCIONXOFICINA")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class V_ATENCIONXOFICINA
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new V_ATENCIONXOFICINA object.
    ''' </summary>
    ''' <param name="sUCURSAL">Initial value of the SUCURSAL property.</param>
    ''' <param name="iDDETALLE_SUCURSAL_OFICINA">Initial value of the IDDETALLE_SUCURSAL_OFICINA property.</param>
    ''' <param name="fECHAHORA_PETICION">Initial value of the FECHAHORA_PETICION property.</param>
    Public Shared Function CreateV_ATENCIONXOFICINA(sUCURSAL As Global.System.String, iDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal, fECHAHORA_PETICION As Global.System.DateTime) As V_ATENCIONXOFICINA
        Dim v_ATENCIONXOFICINA as V_ATENCIONXOFICINA = New V_ATENCIONXOFICINA
        v_ATENCIONXOFICINA.SUCURSAL = sUCURSAL
        v_ATENCIONXOFICINA.IDDETALLE_SUCURSAL_OFICINA = iDDETALLE_SUCURSAL_OFICINA
        v_ATENCIONXOFICINA.FECHAHORA_PETICION = fECHAHORA_PETICION
        Return v_ATENCIONXOFICINA
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DEPARTAMENTO() As Global.System.String
        Get
            Return _DEPARTAMENTO
        End Get
        Set
            OnDEPARTAMENTOChanging(value)
            ReportPropertyChanging("DEPARTAMENTO")
            _DEPARTAMENTO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("DEPARTAMENTO")
            OnDEPARTAMENTOChanged()
        End Set
    End Property

    Private _DEPARTAMENTO As Global.System.String
    Private Partial Sub OnDEPARTAMENTOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDEPARTAMENTOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MUNICIPIO() As Global.System.String
        Get
            Return _MUNICIPIO
        End Get
        Set
            OnMUNICIPIOChanging(value)
            ReportPropertyChanging("MUNICIPIO")
            _MUNICIPIO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MUNICIPIO")
            OnMUNICIPIOChanged()
        End Set
    End Property

    Private _MUNICIPIO As Global.System.String
    Private Partial Sub OnMUNICIPIOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMUNICIPIOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SUCURSAL() As Global.System.String
        Get
            Return _SUCURSAL
        End Get
        Set
            If (_SUCURSAL <> Value) Then
                OnSUCURSALChanging(value)
                ReportPropertyChanging("SUCURSAL")
                _SUCURSAL = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("SUCURSAL")
                OnSUCURSALChanged()
            End If
        End Set
    End Property

    Private _SUCURSAL As Global.System.String
    Private Partial Sub OnSUCURSALChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSUCURSALChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property OFICINA() As Global.System.String
        Get
            Return _OFICINA
        End Get
        Set
            OnOFICINAChanging(value)
            ReportPropertyChanging("OFICINA")
            _OFICINA = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("OFICINA")
            OnOFICINAChanged()
        End Set
    End Property

    Private _OFICINA As Global.System.String
    Private Partial Sub OnOFICINAChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnOFICINAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE_EMPLEADO() As Global.System.String
        Get
            Return _NOMBRE_EMPLEADO
        End Get
        Set
            OnNOMBRE_EMPLEADOChanging(value)
            ReportPropertyChanging("NOMBRE_EMPLEADO")
            _NOMBRE_EMPLEADO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE_EMPLEADO")
            OnNOMBRE_EMPLEADOChanged()
        End Set
    End Property

    Private _NOMBRE_EMPLEADO As Global.System.String
    Private Partial Sub OnNOMBRE_EMPLEADOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_EMPLEADOChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property GESTION() As Global.System.String
        Get
            Return _GESTION
        End Get
        Set
            OnGESTIONChanging(value)
            ReportPropertyChanging("GESTION")
            _GESTION = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("GESTION")
            OnGESTIONChanged()
        End Set
    End Property

    Private _GESTION As Global.System.String
    Private Partial Sub OnGESTIONChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnGESTIONChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_SUCURSAL_OFICINA() As Global.System.Decimal
        Get
            Return _IDDETALLE_SUCURSAL_OFICINA
        End Get
        Set
            If (_IDDETALLE_SUCURSAL_OFICINA <> Value) Then
                OnIDDETALLE_SUCURSAL_OFICINAChanging(value)
                ReportPropertyChanging("IDDETALLE_SUCURSAL_OFICINA")
                _IDDETALLE_SUCURSAL_OFICINA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDDETALLE_SUCURSAL_OFICINA")
                OnIDDETALLE_SUCURSAL_OFICINAChanged()
            End If
        End Set
    End Property

    Private _IDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FECHAHORA_PETICION() As Global.System.DateTime
        Get
            Return _FECHAHORA_PETICION
        End Get
        Set
            If (_FECHAHORA_PETICION <> Value) Then
                OnFECHAHORA_PETICIONChanging(value)
                ReportPropertyChanging("FECHAHORA_PETICION")
                _FECHAHORA_PETICION = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("FECHAHORA_PETICION")
                OnFECHAHORA_PETICIONChanged()
            End If
        End Set
    End Property

    Private _FECHAHORA_PETICION As Global.System.DateTime
    Private Partial Sub OnFECHAHORA_PETICIONChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnFECHAHORA_PETICIONChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PROMEDIO_ESPERA() As Nullable(Of Global.System.Decimal)
        Get
            Return _PROMEDIO_ESPERA
        End Get
        Set
            OnPROMEDIO_ESPERAChanging(value)
            ReportPropertyChanging("PROMEDIO_ESPERA")
            _PROMEDIO_ESPERA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PROMEDIO_ESPERA")
            OnPROMEDIO_ESPERAChanged()
        End Set
    End Property

    Private _PROMEDIO_ESPERA As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnPROMEDIO_ESPERAChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnPROMEDIO_ESPERAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property PROMEDIO_ATENCION() As Nullable(Of Global.System.Decimal)
        Get
            Return _PROMEDIO_ATENCION
        End Get
        Set
            OnPROMEDIO_ATENCIONChanging(value)
            ReportPropertyChanging("PROMEDIO_ATENCION")
            _PROMEDIO_ATENCION = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PROMEDIO_ATENCION")
            OnPROMEDIO_ATENCIONChanged()
        End Set
    End Property

    Private _PROMEDIO_ATENCION As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnPROMEDIO_ATENCIONChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnPROMEDIO_ATENCIONChanged()
    End Sub

    #End Region

End Class

#End Region


