
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("7195833b-b5c6-4402-a635-f2ba986b82b9")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class EntidadesInsert
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new EntidadesInsert object using the connection string found in the 'EntidadesInsert' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=EntidadesInsert", "EntidadesInsert")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new EntidadesInsert object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "EntidadesInsert")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new EntidadesInsert object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "EntidadesInsert")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property GESTIONES_VENTANILLAS() As ObjectSet(Of GESTIONES_VENTANILLAS)
        Get
            If (_GESTIONES_VENTANILLAS Is Nothing) Then
                _GESTIONES_VENTANILLAS = MyBase.CreateObjectSet(Of GESTIONES_VENTANILLAS)("GESTIONES_VENTANILLAS")
            End If
            Return _GESTIONES_VENTANILLAS
        End Get
    End Property

    Private _GESTIONES_VENTANILLAS As ObjectSet(Of GESTIONES_VENTANILLAS)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the GESTIONES_VENTANILLAS EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToGESTIONES_VENTANILLAS(ByVal gESTIONES_VENTANILLAS As GESTIONES_VENTANILLAS)
        MyBase.AddObject("GESTIONES_VENTANILLAS", gESTIONES_VENTANILLAS)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloGestionesVentanillas", Name:="GESTIONES_VENTANILLAS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class GESTIONES_VENTANILLAS
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new GESTIONES_VENTANILLAS object.
    ''' </summary>
    ''' <param name="iDVENTANILLA">Initial value of the IDVENTANILLA property.</param>
    ''' <param name="iDDETALLE_GESTION_OFICINA">Initial value of the IDDETALLE_GESTION_OFICINA property.</param>
    Public Shared Function CreateGESTIONES_VENTANILLAS(iDVENTANILLA As Global.System.Decimal, iDDETALLE_GESTION_OFICINA As Global.System.Decimal) As GESTIONES_VENTANILLAS
        Dim gESTIONES_VENTANILLAS as GESTIONES_VENTANILLAS = New GESTIONES_VENTANILLAS
        gESTIONES_VENTANILLAS.IDVENTANILLA = iDVENTANILLA
        gESTIONES_VENTANILLAS.IDDETALLE_GESTION_OFICINA = iDDETALLE_GESTION_OFICINA
        Return gESTIONES_VENTANILLAS
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDVENTANILLA() As Global.System.Decimal
        Get
            Return _IDVENTANILLA
        End Get
        Set
            If (_IDVENTANILLA <> Value) Then
                OnIDVENTANILLAChanging(value)
                ReportPropertyChanging("IDVENTANILLA")
                _IDVENTANILLA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDVENTANILLA")
                OnIDVENTANILLAChanged()
            End If
        End Set
    End Property

    Private _IDVENTANILLA As Global.System.Decimal
    Private Partial Sub OnIDVENTANILLAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDVENTANILLAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_GESTION_OFICINA() As Global.System.Decimal
        Get
            Return _IDDETALLE_GESTION_OFICINA
        End Get
        Set
            If (_IDDETALLE_GESTION_OFICINA <> Value) Then
                OnIDDETALLE_GESTION_OFICINAChanging(value)
                ReportPropertyChanging("IDDETALLE_GESTION_OFICINA")
                _IDDETALLE_GESTION_OFICINA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDDETALLE_GESTION_OFICINA")
                OnIDDETALLE_GESTION_OFICINAChanged()
            End If
        End Set
    End Property

    Private _IDDETALLE_GESTION_OFICINA As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_GESTION_OFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_GESTION_OFICINAChanged()
    End Sub

    #End Region

End Class

#End Region


