
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("a28f994f-66f3-4524-b7a9-2f34d567bb36")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class EntidadesVistas
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new EntidadesVistas object using the connection string found in the 'EntidadesVistas' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=EntidadesVistas", "EntidadesVistas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new EntidadesVistas object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "EntidadesVistas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new EntidadesVistas object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "EntidadesVistas")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property V_DATOS_UBICACION() As ObjectSet(Of V_DATOS_UBICACION)
        Get
            If (_V_DATOS_UBICACION Is Nothing) Then
                _V_DATOS_UBICACION = MyBase.CreateObjectSet(Of V_DATOS_UBICACION)("V_DATOS_UBICACION")
            End If
            Return _V_DATOS_UBICACION
        End Get
    End Property

    Private _V_DATOS_UBICACION As ObjectSet(Of V_DATOS_UBICACION)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property V_SUCURSAL() As ObjectSet(Of V_SUCURSAL)
        Get
            If (_V_SUCURSAL Is Nothing) Then
                _V_SUCURSAL = MyBase.CreateObjectSet(Of V_SUCURSAL)("V_SUCURSAL")
            End If
            Return _V_SUCURSAL
        End Get
    End Property

    Private _V_SUCURSAL As ObjectSet(Of V_SUCURSAL)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the V_DATOS_UBICACION EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToV_DATOS_UBICACION(ByVal v_DATOS_UBICACION As V_DATOS_UBICACION)
        MyBase.AddObject("V_DATOS_UBICACION", v_DATOS_UBICACION)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the V_SUCURSAL EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToV_SUCURSAL(ByVal v_SUCURSAL As V_SUCURSAL)
        MyBase.AddObject("V_SUCURSAL", v_SUCURSAL)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloVistas", Name:="V_DATOS_UBICACION")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class V_DATOS_UBICACION
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new V_DATOS_UBICACION object.
    ''' </summary>
    ''' <param name="iDDETALLE_SUCURSAL_OFICINA">Initial value of the IDDETALLE_SUCURSAL_OFICINA property.</param>
    ''' <param name="nOMBRE">Initial value of the NOMBRE property.</param>
    Public Shared Function CreateV_DATOS_UBICACION(iDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal, nOMBRE As Global.System.String) As V_DATOS_UBICACION
        Dim v_DATOS_UBICACION as V_DATOS_UBICACION = New V_DATOS_UBICACION
        v_DATOS_UBICACION.IDDETALLE_SUCURSAL_OFICINA = iDDETALLE_SUCURSAL_OFICINA
        v_DATOS_UBICACION.NOMBRE = nOMBRE
        Return v_DATOS_UBICACION
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_SUCURSAL_OFICINA() As Global.System.Decimal
        Get
            Return _IDDETALLE_SUCURSAL_OFICINA
        End Get
        Set
            If (_IDDETALLE_SUCURSAL_OFICINA <> Value) Then
                OnIDDETALLE_SUCURSAL_OFICINAChanging(value)
                ReportPropertyChanging("IDDETALLE_SUCURSAL_OFICINA")
                _IDDETALLE_SUCURSAL_OFICINA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDDETALLE_SUCURSAL_OFICINA")
                OnIDDETALLE_SUCURSAL_OFICINAChanged()
            End If
        End Set
    End Property

    Private _IDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE_OFICINA() As Global.System.String
        Get
            Return _NOMBRE_OFICINA
        End Get
        Set
            OnNOMBRE_OFICINAChanging(value)
            ReportPropertyChanging("NOMBRE_OFICINA")
            _NOMBRE_OFICINA = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE_OFICINA")
            OnNOMBRE_OFICINAChanged()
        End Set
    End Property

    Private _NOMBRE_OFICINA As Global.System.String
    Private Partial Sub OnNOMBRE_OFICINAChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_OFICINAChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            If (_NOMBRE <> Value) Then
                OnNOMBREChanging(value)
                ReportPropertyChanging("NOMBRE")
                _NOMBRE = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("NOMBRE")
                OnNOMBREChanged()
            End If
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE_MPIO() As Global.System.String
        Get
            Return _NOMBRE_MPIO
        End Get
        Set
            OnNOMBRE_MPIOChanging(value)
            ReportPropertyChanging("NOMBRE_MPIO")
            _NOMBRE_MPIO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE_MPIO")
            OnNOMBRE_MPIOChanged()
        End Set
    End Property

    Private _NOMBRE_MPIO As Global.System.String
    Private Partial Sub OnNOMBRE_MPIOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_MPIOChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ModeloVistas", Name:="V_SUCURSAL")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class V_SUCURSAL
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new V_SUCURSAL object.
    ''' </summary>
    ''' <param name="nOMBRE">Initial value of the NOMBRE property.</param>
    ''' <param name="iDMUNICIPIO">Initial value of the IDMUNICIPIO property.</param>
    Public Shared Function CreateV_SUCURSAL(nOMBRE As Global.System.String, iDMUNICIPIO As Global.System.Decimal) As V_SUCURSAL
        Dim v_SUCURSAL as V_SUCURSAL = New V_SUCURSAL
        v_SUCURSAL.NOMBRE = nOMBRE
        v_SUCURSAL.IDMUNICIPIO = iDMUNICIPIO
        Return v_SUCURSAL
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDSUCURSAL() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDSUCURSAL
        End Get
        Set
            OnIDSUCURSALChanging(value)
            ReportPropertyChanging("IDSUCURSAL")
            _IDSUCURSAL = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDSUCURSAL")
            OnIDSUCURSALChanged()
        End Set
    End Property

    Private _IDSUCURSAL As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDSUCURSALChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDSUCURSALChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            If (_NOMBRE <> Value) Then
                OnNOMBREChanging(value)
                ReportPropertyChanging("NOMBRE")
                _NOMBRE = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("NOMBRE")
                OnNOMBREChanged()
            End If
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDMUNICIPIO() As Global.System.Decimal
        Get
            Return _IDMUNICIPIO
        End Get
        Set
            If (_IDMUNICIPIO <> Value) Then
                OnIDMUNICIPIOChanging(value)
                ReportPropertyChanging("IDMUNICIPIO")
                _IDMUNICIPIO = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDMUNICIPIO")
                OnIDMUNICIPIOChanged()
            End If
        End Set
    End Property

    Private _IDMUNICIPIO As Global.System.Decimal
    Private Partial Sub OnIDMUNICIPIOChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDMUNICIPIOChanged()
    End Sub

    #End Region

End Class

#End Region


